### ISSUE TITLE
Single band nuclei detection should use consistent scaling across image

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/HistomicsTK#1002]
One of the reasons we want to calculate a whole-image scaling parameter is to avoid processing differences on different tiles.

**Comment by manthey** [comment]
> If we go inside the `detect_nuclei_with_dask` -->`detect_tile_nuclei` there is already a checkpoint that stacks a single-channel image to RGB. I have added casting to that code. Now the input for Reinhard normalization will be of the desired dtype and in 3 channel format.

I don't think we have to do this cast unless the code is going to use `skimage.rgb2lab`; I think the other code handles the floating point values that aren't scaled [0,1], so the cast just uses more time and memory.

**Comment by subinkitware** [comment]
After the casting process, the input goes into `htk_cnorm.reinhard` that has an inbuild `rgb_to_lab` coming from the `preprocessing` module. Inside that function, there is a dot product between the log of the image and the array. I believe that the casting could be helpful there.
