### ISSUE TITLE
No module named 'histomicstk.segmentation.label._trace_object_boundaries_cython'

### ISSUE THREAD

**Issue by vinhtien** [DigitalSlideArchive/HistomicsTK#1008]
Hi,

I am installing HIstomicsTK in Anaconda (Windows 10, Python 3.9) using the introduction from README
Installation seems fine without error.

However, I got the below error when importing the histomicstk in Python after installation.

(ldsa) PS E:\admin\HistomicsTK> python
Python 3.9.17 (main, Jul  5 2023, 20:47:11) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import histomicstk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\admin\HistomicsTK\histomicstk\__init__.py", line 2, in <module>
    from . import segmentation  # must be imported before features
  File "E:\admin\HistomicsTK\histomicstk\segmentation\__init__.py", line 11, in <module>
    from . import label, level_set, nuclear, positive_pixel_count
  File "E:\admin\HistomicsTK\histomicstk\segmentation\label\__init__.py", line 18, in <module>
    from .trace_object_boundaries import trace_object_boundaries
  File "E:\admin\HistomicsTK\histomicstk\segmentation\label\trace_object_boundaries.py", line 3, in <module>
    from ._trace_object_boundaries_cython import _trace_object_boundaries_cython
ModuleNotFoundError: No module named 'histomicstk.segmentation.label._trace_object_boundaries_cython'

Could someone knows how to solve this issue?

Thank you!

**Comment by hannah413** [comment]
hey, i had this same error message on import within linux. i had built histomicstk from source. i uninstalled it completely and rm -rf'd it for good measure. then with my conda's installation of pip, i resolved the issue by reinstalling it like this:

`pip install --histomicstk --find-links https://girder.github.io/large_image_wheels`

now i can import just fine.
