### ISSUE TITLE
Ensure each cli runs without needing to set anything

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/HistomicsTK#1030]
Ideally, each CLI would run in the HistomicsUI without any changes to its settings; they may not be optimal, but they would throw any errors.  I would test this on a TCGA image that is a reasonably large size.  Additionally, if the CLI supports using a rectangular ROI, it should run without any changes except setting that ROI.

List of CLI's to be updated.

- [x] background intensity (updated the sample fraction amount)
- [x] color deconvolution
- [x] compute nuclei features (mathey updated the features library)
- [x] positive pixel count (updated-pending approval)
- [x] separate stains Xusnmf (defaults already present in the code)
- [x] superpixel segmentation (defaults already present in the code)

**Comment by subinkitware** [comment]
List of CLI's to be updated.

- [ ] background intensity (updated the sample fraction amount)
- [ ] color deconvolution 
- [ ] compute nuclei features (mathey updated the features library)
- [ ] positive pixel count
- [ ] nuclei classification (need some extra files to run the cli)
- [ ] separate stains Xusnmf
- [ ] superpixel segmentation
