### ISSUE TITLE
Profile Positive Pixel Count

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/HistomicsTK#1031]
We have a report from the field that the positive pixel count algorithm is slower than expected.

It looks like the bulk of the time is in the `large_image_source_vips.write()` method; specifically when vips is used to `write_to_file`.  Would using a different lossless compression scheme be substantially faster?  Would using a different tile size for computation be faster?  Would reducing memory use help?

**Comment by manthey** [comment]
For starters, just see how different tile sizes affect the total time.   I'd try powers of two on either side of what is currently used.

**Comment by subinkitware** [comment]
@manthey 
On testing  a medium-sized WSI with Positive pixel count- (size of 645MB)

- Tile size 1032 - Total analysis time > 15 min (3 min image processing)
- Tile size 2048 - Total analysis time = 9 min ( 4 min image processing, 5-minute image saving)
- Tile size 4086 - Total analysis time = 7 min ( 5 min image processing, 2 min image saving)

_There is a 22% time saving on changing on doubling the tile size without much overload to a 16GB RAM_

- Tile size 8192 - Fills the ram of a 16 GB system and process moves to swap. slower than the above if the system specs are basic. 

If you agree that 22% decrease in total execution time is good number for researchers, I could update the tile size to 4086

**Comment by manthey** [comment]
Did you actually use 1032, 2048, 4086, 8192?  I would have expected powers of two: *1024*, 2048, *4096*, 8192.

How many cores did your test system have?  I ask because the memory is probably linear with cores or virtual cores, and the bigger tiles might saturate a high-core count system that doesn't have a commensurately larger memory.

**Comment by subinkitware** [comment]
> Did you actually use 1032, 2048, 4086, 8192? I would have expected powers of two: _1024_, 2048, _4096_, 8192.
> 
> How many cores did your test system have? I ask because the memory is probably linear with cores or virtual cores, and the bigger tiles might saturate a high-core count system that doesn't have a commensurately larger memory.

That numbers were a mistake, I did some mind calculation. I originally used 1024, 2048..etc in the code. My laptop is having an i-9 processor with 8 cores (16 threads), 16 GB ram, and 65GB of swap.

**Comment by manthey** [comment]
Yes.  Let's change it to 4096.
