### ISSUE TITLE
How to get started with fetching region of interest drawn by user and replacing it with resultant region returned by python after processing

### ISSUE THREAD

**Issue by abhisheklomsh** [DigitalSlideArchive/HistomicsTK#1056]
I am trying to use custom models along with DSA & Histomics, seeking suggestion on where to get started / boiler code to fetch and paste results, I will be using Whole Slide Images.

**Comment by manthey** [comment]
This is sort of two questions.  You can make a CLI which takes an input image and an ROI and outputs an image.  The basic approach is something like shown in one of these simpler examples: https://github.com/girder/slicer_cli_web/tree/master/example-average-color
but you'd add an output image record (see some of the cli examples in this repo).

If you are using the ctk-cli module for arg parsing (e.g, `from ctk_cli import CLIArgumentParser` or `from histomicstk.cli.utils import CLIArgumentParser`, and then `args = CLIArgumentParser().parse_args()`, you'll have a namespace with your input and output parameters.

See https://github.com/DigitalSlideArchive/HistomicsTK/blob/master/histomicstk/cli/PositivePixelCount/PositivePixelCount.py for an example that does this and handles complex ROIs.

You could do something like:
```
import large_image
from ctk_cli import CLIArgumentParser

# This reads the companion xml file and parses the command line arguments
args = CLIArgumentParser().parse_args()
source = large_image.open(args.inputImage)
output = large_image.new()
for tile in source.tileIterator(format=large_image.tilesource.TILE_FORMAT_NUMPY):
    # choose what to do with the tile based on args.roi and tile['x'], tile['y'], tile['width'], tile['height'],
    processedTile = some_process_function(tile['tile'])
    output.addTile(processedTile, tile['x'], tile['y'])
output.write(args.outputImagePath)
```

**Comment by manthey** [comment]
I'll close this as an issue.  We recently created a discussion board (https://github.com/DigitalSlideArchive/digital_slide_archive/discussions).  Feel free to ask more questions there.
