### ISSUE TITLE
histomics wheels can't be found at https://girder.github.io/large_image_wheels any more

### ISSUE THREAD

**Issue by iRyoka** [DigitalSlideArchive/HistomicsTK#1114]
large_image_wheels links page does not contain wheels for any versions of histomicstk, which was the only easy way to install histomicstk. Could you provide another source for wheels?

**Comment by manthey** [comment]
Histomicstk wheels are on pypi (they've never been on the large_image_wheels page).

**Comment by iRyoka** [comment]
Oh, my bad then, thank you!
