### ISSUE TITLE
calculation error while computing haralick features for a set of images

### ISSUE THREAD

**Issue by me-nobody** [DigitalSlideArchive/HistomicsTK#1116]
![image](https://github.com/DigitalSlideArchive/HistomicsTK/assets/7254581/87d49fa8-b266-406d-a2aa-e4bc6bf69ade)
[predict_nuclei_multiple-118519_err.txt](https://github.com/user-attachments/files/15973689/predict_nuclei_multiple-118519_err.txt)
![predicted_label](https://github.com/DigitalSlideArchive/HistomicsTK/assets/7254581/47e8fbf0-1799-4cea-ae93-43c8934b5fec)
Hi,
for a set of images, when I used histomicsTK, it threw a calculation error.  Can you please tell me how to overcome this error. I have uploaded the image, the label image and the error.
Best 
Anu

**Comment by manthey** [comment]
It looks like this happens with some floating point rounding errors.  I added a PR that guards against it.
