### ISSUE TITLE
New error when trying to pip install HistomicsTK - rasterio failing

### ISSUE THREAD

**Issue by pearcetm** [DigitalSlideArchive/HistomicsTK#1127]
Since rasterio released v 1.3.11 ~10 hours ago, HistomicsTK installation is failing. Maybe a wheels problem? Any idea why and how to fix it?

**Comment by manthey** [comment]
Hmm...  I just did an install in a fresh environment and had no issue.  What python version and OS are you on?

**Comment by pearcetm** [comment]
This is being installed in a docker container running linux with a base image `nvidia/cuda:11.0.3-cudnn8-runtime-ubuntu20.04`; it would be using whatever version of python3 that comes with that image since we're not specifying further.

**Comment by manthey** [comment]
I assume you are apt-getting the default python3 in that image, which is python 3.8.  rasterio stopped publishing 3.8 wheels.  I'll add a version pin upstream in large_image so for Python 3.8 we specify an older version of rasterio.  This will take a while to percolate through to the HistomicsTK packages.

In the meantime, either use a newer python or specify `--prefer-binary` as part of your pip install command.

**Comment by pearcetm** [comment]
Thanks for tracking this down. In the short term, `--prefer-binary` worked to get my whole build working again.

**Comment by manthey** [comment]
And, with a new release of large_image, this will no longer have the issue even without `--prefer-binary`.
