### ISSUE TITLE
Fix docstring of CompactLabel

### ISSUE THREAD

**Issue by cdeepakroy** [DigitalSlideArchive/HistomicsTK#149]
The docstring of [CompactLabel](https://github.com/DigitalSlideArchive/HistomicsTK/blob/master/histomicstk/segmentation/label/CompactLabel.py#L7-L8) is same as [SplitLabel](https://github.com/DigitalSlideArchive/HistomicsTK/blob/master/histomicstk/segmentation/label/SplitLabel.py#L8-L9) while it does something else inside.

**Comment by cooperlab** [comment]
Fixed by PR #150
