### ISSUE TITLE
Add Haralick features to ComputeNucleiFeatures

### ISSUE THREAD

**Issue by cdeepakroy** [DigitalSlideArchive/HistomicsTK#159]
@slee172 Can you add please Haralick features to ComputeNucleiFeatures?

**Comment by slee172** [comment]
@cdeepakroy OK. 

Can you see "scipy.stats.iqr" in ComputeIntensityFeatures.py ? It seems not to run on scipy-0.16. It works scipy-0.18 well.

**Comment by slee172** [comment]
@cdeepakroy Can you see [this](https://github.com/DigitalSlideArchive/HistomicsTK/blob/master/histomicstk/features/graycomatrixext.py#L170) ? I got an error "ValueError: invalid entry in coordinates array" when "neigh_coord_ind" exceeds "im_roi_mask.shape". How about adding the parameter mode on it. For example, np.ravel_multi_index(neigh_coord_ind, im_roi_mask.shape mode='clip') as default?

**Comment by slee172** [comment]
the problem above is solved

**Comment by slee172** [comment]
Made a PR on #160
