### ISSUE TITLE
Improving routing to include form and image information

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/HistomicsTK#166]
Include image bounds and rotation.  Include form values

**Comment by jbeezley** [comment]
How should the URL history be handled?  Should all changes in the form and image bounds push a new browser history entry or should it just replace the current URL?

I think the implementation of this depends pretty heavily on what its primary purpose is.  For example, if we just want a permalink to the current state of the page, replacing the URL is sufficient.  If we just want to preserve the state while navigating (or between sessions), a localStorage approach would work.  If we want the user to be able to back out of recent changes, we need to push history, but what is the resolution of the save points?

**Comment by manthey** [comment]
I know we want this for permalinks.  I don't think we discussed other uses yet.

**Comment by jbeezley** [comment]
Okay, I can start by replacing the URL state without pushing to history, and we can iterate from there.

**Comment by manthey** [comment]
I'm closing this.  We don't currently url encode form data, but we do encode image information.  If we want other state, we can add new issues.
