### ISSUE TITLE
Need count() endpoint for items/folders to support paging

### ISSUE THREAD

**Issue by dgutman** [DigitalSlideArchive/HistomicsTK#173]
In order to properly implement client side paging, we need to be able to first check how many items()/objects a given endpoint would return.... 

We already support limit and offset--- however no method to actually get the count.. .which means in order to use those fields you need to first get everything and then page it... or increment by some random amount till you stop getting data back...

Parameters
Parameter   Value   Description Parameter Type  Data Type
id  
(required)
The ID of the item. path    string
limit  
50
Result set size limit.  query   integer
offset  
0
Offset into result set. query   integer
sort  
name
Field to sort the result set by.    query   string
sortdir     Sort order: 1 for ascending, -1 for descending. query   integer

**Comment by manthey** [comment]
This feature has been added by https://github.com/girder/girder/pull/2614.  Most queries now include a response header `Girder-Total-Count` which contains the total number of resources.
