### ISSUE TITLE
pip installation error: could not find a version that satisfies the requirement histomicstk

### ISSUE THREAD

**Issue by evanbiederstedt** [DigitalSlideArchive/HistomicsTK#178]
Hi

Trying to install via pip 8.1.2 via the Python2.7 and Python3.4 versions fails. 

```
$ pip install histomicstk
```

outputs 

```
Collecting histomicstk
  Could not find a version that satisfies the requirement histomicstk (from versions: )
No matching distribution found for histomicstk
```

Similarly with 

```
sudo pip install git+https://github.com/DigitalSlideArchive/HistomicsTK.git
```

this outputs the error: 

```
....
Collecting ctk-cli==1.3.1 (from histomicstk==0.1.0)
  Could not find a version that satisfies the requirement ctk-cli==1.3.1 (from histomicstk==0.1.0) (from versions: 1.0, 1.1, 1.2, 1.3)
No matching distribution found for ctk-cli==1.3.1 (from histomicstk==0.1.0)
```

though the most current version of `ctk-cli` is installed.

**Comment by cdeepakroy** [comment]
@evanbiederstedt HistomicsTK is not on PyPi yet which is the reason `pip install histomicstk` is not working. We are waiting on a few things to be developed before we release it on PyPi. 

ctk_cli version 1.3.1 is also not on PyPi yet. Here is the [PR](https://github.com/commontk/ctk-cli/pull/8) for it. While that gets merged, you can install it either from [this](https://github.com/cdeepakroy/ctk-cli) git repo or through conda as shown [here](https://anaconda.org/cdeepakroy/ctk-cli).

After that install HistomicsTK through the following steps:
```
git clone git@github.com:DigitalSlideArchive/HistomicsTK.git
cd HistomicsTK
conda install --yes libgfortran==1.0 --file requirments_c_conda.txt
pip install -r requirements.txt -r requirments_c.txt
python setup.py install
```
After the aforementioned steps, you should be able to `import histomicstk` and use any of the algorithm functionality in it.

We are trying to use vagrant/ansible to ease the installation of HistomicsTK and other packages that it is being developed in tight coordination with such as the [large_image](https://github.com/DigitalSlideArchive/large_image), [girder_worker](https://github.com/girder/girder_worker), and [girder](https://github.com/girder/girder). 

You can now test this by going through the following steps that will give you a vagrant box (aka virtual box) with everything installed:
* Install virtual box from here - https://www.virtualbox.org/wiki/Downloads
* Download and install vagrant from here - https://www.vagrantup.com/downloads.html
* `pip install ansible`
* `git clone git@github.com:DigitalSlideArchive/HistomicsTK.git`
* `cd HistomicsTK && vagrant up`
* `vagrant ssh`
* `cd /opt/histomicstk && ls`

We are yet to fix the documentation (including the one about [installation](https://histomicstk.readthedocs.io/en/latest/installation.html)) on ReadTheDocs. In the near future, we will include a few demos to help new users up and running.

Let us know if you face any issues.
