### ISSUE TITLE
Port forwarding error with vagrant/ansible provisioning

### ISSUE THREAD

**Issue by cdeepakroy** [DigitalSlideArchive/HistomicsTK#189]
When i tried to provision HistomicsTK on my ubuntu 14.04, I get the following error:

> (emory)cdeepakroy:~/emory/code/test_vagrant/HistomicsTK$ vagrant up
> Bringing machine 'default' up with 'virtualbox' provider...
> ==> default: Importing base box 'ubuntu/trusty_64'...
> ==> default: Matching MAC address for NAT networking...
> ==> default: Setting the name of the VM: HistomicsTK Ubuntu 14.04
> ==> default: Clearing any previously set forwarded ports...
> Vagrant cannot forward the specified ports on this VM, since they
> would collide with some other application that is already listening
> on these ports. The forwarded port to 2209 is already in use
> on the host machine.
> 
> To fix this, modify your current project's Vagrantfile to use another
> port. Example, where '1234' would be replaced by a unique host port:
> 
>   config.vm.network :forwarded_port, guest: 22, host: 1234
> 
> Sometimes, Vagrant will attempt to auto-correct this for you. In this
> case, Vagrant was unable to. This is usually because the guest machine
> is in a state which doesn't allow modifying port forwarding. You could
> try 'vagrant reload' (equivalent of running a halt followed by an up)
> so vagrant can attempt to auto-correct this upon booting. Be warned
> that any unsaved work might be lost.
> 

CC: @zachmullen @manthey

**Comment by zachmullen** [comment]
It's telling you that you already have something on your host listening on port 2209, which is where we forward the SSH port from the guest. We can change it to some other port, it probably won't affect anyone since people mostly just do `vagrant ssh`.

**Comment by manthey** [comment]
You have another VirtualBox running (probably one you vagrant up-ed earlier) which causes the problem.   I like having a specified port for this, so I can easily ssh between two VMs (or, more typically, scp).  It would be nice to make this optional, so if it is already in use it fails gracefully.

**Comment by cdeepakroy** [comment]
You were right. There was a Virtualbox (from previous vagrant up) running that caused this issue. I followed the stackoverflow solution described [here](http://stackoverflow.com/a/16876318)

**Comment by zachmullen** [comment]
Was it from HistomicsTK in a different directory? If you `vagrant up` from the same directory twice, it should just tell you that it's already running.

**Comment by cdeepakroy** [comment]
Yes i tried in a different directory earlier. So that must have stayed. I will close this issue now that this problem is resolved. 

I created a new issue for another error i am facing.
