### ISSUE TITLE
ssh private key permissions error on vagrant/ansible provisioning

### ISSUE THREAD

**Issue by cdeepakroy** [DigitalSlideArchive/HistomicsTK#190]
I get the following error after git cloning HistomicsTK and doing vagrant up on my ubuntu 14.04:

> Bringing machine 'default' up with 'virtualbox' provider...
> ==> default: Importing base box 'ubuntu/trusty_64'...
> ==> default: Matching MAC address for NAT networking...
> ==> default: Setting the name of the VM: HistomicsTK Ubuntu 14.04
> ==> default: Clearing any previously set forwarded ports...
> ==> default: Clearing any previously set network interfaces...
> ==> default: Preparing network interfaces based on configuration...
>     default: Adapter 1: nat
> ==> default: Forwarding ports...
>     default: 22 (guest) => 2209 (host) (adapter 1)
>     default: 8009 (guest) => 8009 (host) (adapter 1)
>     default: 22 (guest) => 2222 (host) (adapter 1)
> ==> default: Running 'pre-boot' VM customizations...
> ==> default: Booting VM...
> ==> default: Waiting for machine to boot. This may take a few minutes...
>     default: SSH address: 127.0.0.1:2222
>     default: SSH username: vagrant
>     default: SSH auth method: private key
>     default: Warning: Remote connection disconnect. Retrying...
>     default: 
>     default: Vagrant insecure key detected. Vagrant will automatically replace
>     default: this with a newly generated keypair for better security.
>     default: 
>     default: Inserting generated public key within guest...
>     default: Removing insecure key from the guest if it's present...
>     default: Key inserted! Disconnecting and reconnecting using new SSH key...
> The private key to connect to the machine via SSH must be owned
> by the user running Vagrant. This is a strict requirement from
> SSH itself. Please fix the following key to be owned by the user
> running Vagrant:
> 
> /media/common/EmoryImageAnnotationPlatform/code/test_vagrant/HistomicsTK/.vagrant/machines/default/virtualbox/private_key

[Here](http://stackoverflow.com/questions/35964050/private-key-to-connect-to-the-machine-via-ssh-must-be-owned-by-the-user-running) is a stackoverflow post with the same issue.

/media/common is an NTFS partition shared between windows 7 and ubuntu 14.04. So, I am [not able to](http://stackoverflow.com/questions/8852344/how-can-i-use-chmod-command-under-the-ntfs-file-system) change the permission of `/media/common/EmoryImageAnnotationPlatform/code/test_vagrant/HistomicsTK/.vagrant/machines/default/virtualbox/private_key
`

Permissions before chown

> (emory)cdeepakroy:~/emory/code/test_vagrant/HistomicsTK$ stat /media/common/EmoryImageAnnotationPlatform/code/test_vagrant/HistomicsTK/.vagrant/machines/default/virtualbox/private_key
>   File: ‘/media/common/EmoryImageAnnotationPlatform/code/test_vagrant/HistomicsTK/.vagrant/machines/default/virtualbox/private_key’
>   Size: 1679          Blocks: 8          IO Block: 4096   regular file
> Device: 805h/2053d    Inode: 146953      Links: 1
> Access: (0777/-rwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
> Access: 2016-09-08 10:33:42.782939100 -0400
> Modify: 2016-09-08 10:33:42.783257200 -0400
> Change: 2016-09-08 10:33:42.783257200 -0400
>  Birth: -

Permissions after chown

> (emory)cdeepakroy:~/emory/code/test_vagrant/HistomicsTK$ chown `whoami` /media/common/EmoryImageAnnotationPlatform/code/test_vagrant/HistomicsTK/.vagrant/machines/default/virtualbox/private_key
> (emory)cdeepakroy:~/emory/code/test_vagrant/HistomicsTK$ stat /media/common/EmoryImageAnnotationPlatform/code/test_vagrant/HistomicsTK/.vagrant/machines/default/virtualbox/private_key
>   File: ‘/media/common/EmoryImageAnnotationPlatform/code/test_vagrant/HistomicsTK/.vagrant/machines/default/virtualbox/private_key’
>   Size: 1679          Blocks: 8          IO Block: 4096   regular file
> Device: 805h/2053d    Inode: 146953      Links: 1
> Access: (0777/-rwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
> Access: 2016-09-08 10:33:42.782939100 -0400
> Modify: 2016-09-08 10:33:42.783257200 -0400
> Change: 2016-09-08 10:33:42.783257200 -0400
>  Birth: -

**Comment by cdeepakroy** [comment]
CC: @zachmullen @manthey

**Comment by zachmullen** [comment]
Is it possible to copy the HistomicsTK clone somewhere that isn't on the shared NTFS?

**Comment by cdeepakroy** [comment]
I am trying it on my home directory now to see if it goes away.  I am also trying sudo vagrant up since that private_key file seems to be owned by root.

But i think this is restricting for dual boot systems. My shared NTFS partition has the most disk space. The ubuntu partition has a minimal amount needed to run the OS and Applications.

**Comment by cdeepakroy** [comment]
vagrant up in home directory produces the following error:

> TASK [girder : Download nodejs install script] *********************************
> fatal: [default]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to validate the SSL certificate for deb.nodesource.com:443. Make sure your managed systems have a valid CA certificate installed. If the website serving the url uses SNI you need python >= 2.7.9 on your managed machine or you can install the `urllib3`, `pyopenssl`, `ndg-httpsclient`, and `pyasn1` python modules to perform SNI verification in python >= 2.6. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible"}
>

**Comment by cdeepakroy** [comment]
Looks like it is the same error referenced in issue #188
