### ISSUE TITLE
Input images to analysis modules in front-end are restricted to large images

### ISSUE THREAD

**Issue by cdeepakroy** [DigitalSlideArchive/HistomicsTK#196]
I was trying to run one of the analysis modules on simple .png image via the front-end.

However, the input images seem to be restricted only to a large_image

![large_image_images_only](https://cloud.githubusercontent.com/assets/1923534/18403100/e0b5b612-76b0-11e6-80d6-a709c6599232.png)

I think this is coming from [here](https://github.com/DigitalSlideArchive/HistomicsTK/blob/cd6dd569f48ffa962249c2c5f9453a1dd55127ae/web_client/js/views/itemSelectorWidget.js#L60)

The analysis modules do not work on large images yet. In any case, I feel this restriction should not be enforced. I foresee that users would like to try algorithms on smaller tiles first to get the parameters right, and then run it on the whole slide which takes a lot of computational time.

CC: @jbeezley

**Comment by jbeezley** [comment]
The main reason it depends on the item being tagged as a large image is to get a reference to the actual image file in the item.  The [next line](https://github.com/DigitalSlideArchive/HistomicsTK/blob/cd6dd569f48ffa962249c2c5f9453a1dd55127ae/web_client/js/views/itemSelectorWidget.js#L65) in the code actually takes care of sending to the analysis the original (not tiled) image.  Is there any reason you can't just tag the png image as a large image like we did for the demo a few months ago?  I think trying to support arbitrary items in the UI would be more trouble than it's worth.

**Comment by cdeepakroy** [comment]
Since we are working on moving this automatic widget generation functionality to slicer_cli_web where it might be used by other projects to run analysis on other types of images (e.g. radiology - MRI, CT, PET), requiring them to be tagged as a large_image would probably not be appropriate.

**Comment by manthey** [comment]
For the non-Girder access side of things, we could add a source to large_image that would handle non-tiled images like they were a tiled images of one layer.  I'd put a limit on the maximum number of pixels that such an image could be, as we need for the image to fit in memory.  This would allow the same back-end methods to be used on the image (such as getRegion, getThumbnail, and tileIterator).

If we added a 'handle small images as one-tile images' option to large_image and make this on by default, then uploading a PNG would mark it as a one-tile 'large image' which would then just work under the current set-up.

**Comment by jbeezley** [comment]
For other plugins using the UI without large image, we could add a constructor parameter that disables the check.  It would then be up to the application to disambiguate which file to choose from the item.

I'll do this for HistomicsTK if you really want, but I'll put my vote in that it's a bad idea.  I don't like relying on behavior that isn't guaranteed by the API.  Sure 99.9% of the time, using the first file from the item will be fine, but somebody will hit the 0.1% at some point.

**Comment by cdeepakroy** [comment]
@manthey I like your ` 'handle small images as one-tile images` solution. That way we can use the  `getTileSource, getRegion, tileIterator etc` for reading regardless of the kind of image.

@jbeezley The constructor parameter to optionally disable the check would be good for now. That way when we face the radiology use case we can think of a better solution.

In the radiology use case, I think there are two kinds image formats:
-- The entire volume is stored in one file (ex: .nrrd, .mha).
-- DICOM - The image data is stored in multiple .dcm files.

**Comment by jbeezley** [comment]
i'll add that to my branch over in `slicer_cli_web`.  I have the code moved over there, I just need to update this repo to use it, then I'll issue a PR.

**Comment by cdeepakroy** [comment]
This is now resolved!
