### ISSUE TITLE
Disable caching when pip installing via ansible

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/HistomicsTK#206]
We need to flush or ignore the pip cache when installing via ansible.  Otherwise, if Pillow was installed *prior* to installing openslide, then when we ask for Pillow to be installed we get a version which is cached and references the no-longer-existing old jpeg libraries instead of the newly generated jpeg libraries.

**Comment by manthey** [comment]
@zachmullen Do you think we should just disable pip caching in general, or should we flush the pip cache?

@dgutman This is the root of the jpeg-version problem on the two installs you did.

**Comment by zachmullen** [comment]
I'd say we should just flush it prior to doing the pip install.

**Comment by dgutman** [comment]
Aah .. makes sense..
And definitely a bit of package management hell...

**Comment by manthey** [comment]
Resolved in PR #207.
