### ISSUE TITLE
Remove dependency on matplotlib

### ISSUE THREAD

**Issue by cooperlab** [DigitalSlideArchive/HistomicsTK#21]
I don't think we need to require matplotlib for installing histomicstk. This is causing issues installing on our cluster as it tries to pull in all kinds of other packages. People are free to install this independently and there are other options for viewing images.

**Comment by cdeepakroy** [comment]
@cooperlab sure we can remove it.

**Comment by brianhelba** [comment]
One option is to make it a development dependency, so it can be used to generate examples / documentation of algorithm outputs, but it won't be required for an ordinary installation.

Also, I'd still recommend using Conda to get most of the SciPy stack, as it's much faster than building locally.

**Comment by cooperlab** [comment]
This sounds like the best approach. It is really only required for display in the examples.

________________________________
