### ISSUE TITLE
Slide manual annotation

### ISSUE THREAD

**Issue by fedorov** [DigitalSlideArchive/HistomicsTK#215]
Is it possible to manually annotate with region contours and save annotations on slides using HistomicsTK?

If not, is this a planned feature and what is the timeline?

Sorry if I missed this in the documentation.

**Comment by manthey** [comment]
Manual annotations are going to be added soon -- probably within a few weeks.

**Comment by fedorov** [comment]
Thank you very much - I look forward to this feature!

**Comment by dgutman** [comment]
We just need to finalize the annotation format.. we've been kicking it
around for a long time in an ad hoc fashion... But now want to make sure we
are properly validating it all.. will let you know when we get a wip up..

**Comment by fedorov** [comment]
> Manual annotations are going to be added soon -- probably within a few weeks.

Hey guys, is there an updated timeline for this topic? The comment above is from Oct 2016.

**Comment by manthey** [comment]
Added in PR #296.
