### ISSUE TITLE
Fix seeding of elongated cells in GaussianVoting.py

### ISSUE THREAD

**Issue by cooperlab** [DigitalSlideArchive/HistomicsTK#24]
Elongated cells are not being detected properly by GaussianVoting. Their symmetry is more axial than radial, and the votes are too diffuse to be detected as seed locations.

**Comment by cdeepakroy** [comment]
@cooperlab have you seen [this](http://dosen.narotama.ac.id/wp-content/uploads/2014/10/A-Generalized-Laplacian-of-Gaussian-Filter.pdf) method which uses a Generalized version of Laplacian of Gaussian filter that gives the blob/nuclei seed points, scale, and also the orientation. Seems a good approach for really elongated nuclei but the downside is it could be a bit slower than just LoG.

**Comment by cooperlab** [comment]
Thanks Deepak - I will take a look. We can always find ways to make things faster.

________________________________

**Comment by cooperlab** [comment]
I think the convolutions can be accelerated as following:
-The second derivatives of the gaussians are "steerable" - i.e. any arbitrary orientation can be reconstructed by a linear combination of three basis functions.
-At least two of the basis functions can be represented with separable convolutions

This should put the computation time within reach. I will implement this the naive way and then we can branch & optimize later.

**Comment by cooperlab** [comment]
This is an inherent weakness of the Gaussian Voting method. The proposed alternative was implemented in pull request #54
