### ISSUE TITLE
Add a slider for magnification of whole-slide images in the HistomicsTK front-end 

### ISSUE THREAD

**Issue by cdeepakroy** [DigitalSlideArchive/HistomicsTK#253]
This issue is about added a slider for magnification of whole-slide images. The slider should show the native magnification levels as ticks and the current magnification (maybe in a text box).

CC: @jbeezley @manthey

**Comment by jbeezley** [comment]
I see the `/item/{id}/tiles` endpoint contains a "magnification" parameter.  I assume that is the native magnification of the image.  Is this is the resolution of the tiles returned at the maximum zoom level?  If not, how do I correlate zoom level with magnification?

Also, how should the slider be displayed?  A linear scale w.r.t. magnification with ticks at integer magnifications?  I'm not sure what you mean by "native magnification levels".

**Comment by cdeepakroy** [comment]
Yes that is the native magnification or the magnification at the highest resolution layer.

The native magnification levels are in log-linear scale i.e. the magnification of each layer is 0.5 times the magnification (down-sampling by 2) of the next higher resolution layer.

Maybe the slider should also be in log-linear scale. The ticks could be at integer magnifications of this scale. If possible, it would be nice to highlight the ticks (maybe bold) of the native magnification levels available.

cc: @cooperlab Any suggestions?

**Comment by manthey** [comment]
The magnification is the objective magnification (which usually assumes a 10x eyepiece magnification) at the maximum zoom level.  We have tiles at resolutions at the powers of 2 of the magnification, and these would be considered the "native" values.  In practice, there are some slide formats that are missing levels, but we currently don't expose the list of which levels are really present anywhere.

It seems like a slider with the distinct zoom levels 20 - 10 - 5 - 2.5 would be appropriate (skipping some if this would be too dense).

**Comment by cooperlab** [comment]
At least in OpenSlide you have the magnification of the base level, then scaling factors for each additional level to do the calculation.

For the slider - I think it's important to at least put ticks on the available magnifications, or at 1.25, 2.5, 5, 10, 20, 40. Would be nice to be able to snap to these. Or to have an adjacent text box where you can type in the magnification.

**Comment by cooperlab** [comment]
@cdeepakroy definitely log linear. Otherwise you can't really slide between lower magnifications effectively.

Aperio has a series of buttons corresponding to the main magnifications. For reference:
http://www.nyee.edu/files/NYEE/Patient%20Care/Other%20Services/Pathology/aperio-07-imagescope.png
