### ISSUE TITLE
Add a menu for creating, loading, and saving annotations

### ISSUE THREAD

**Issue by cdeepakroy** [DigitalSlideArchive/HistomicsTK#254]
This issue is about adding a menu to the HistomicsTK front-end to create, load, and save annotations on whole-slide images.

All annotations in the [annotation schema](https://github.com/girder/large_image/blob/master/docs/annotations.md) of large_image should be supported.

What would also be nice to have, is for region parameters of Slicer CLIs, in addition to the current functionality of clicking a button draw a box, there should also be a way to set the region to rectabgle annotations created via the annotation menu.

CC: @jbeezley @manthey

**Comment by manthey** [comment]
This was added in https://github.com/girder/large_image/pull/354 for the Girder interface.
