### ISSUE TITLE
Implement a CLI for Nuclei Classification

### ISSUE THREAD

**Issue by cdeepakroy** [DigitalSlideArchive/HistomicsTK#285]
The inputs to this CLI should be:
* Whole slide image path
* Nuclei annotation file (*.anot)
* Nuclei feature file (*.hdf5)
* Takes a scikit-learn model file (*.pkl)

The outputs of this CLI should be:
* Outputs an annotation file (*.anot) with +ve nuclei in one color and -ve nuclei in another color
* Outputs probability map at low-res that will be rendered as a heat map

**Comment by cooperlab** [comment]
@neal-siekierski here is a link to the heatmap generation we created for cell classification with the active learning system:
[https://github.com/cooperlab/ActiveLearning/blob/8508d8cb938d5c39fa59ca612850e7a0adc0f36e/al_server/src/learner.cpp#L2434](url)

A lot of trial and error to get the normalization and window sizes correct.

**Comment by manthey** [comment]
We have a heatmap view in geojs that scales a scalar value over arbitrary points in a field: http://opengeoscience.github.io/geojs/examples/heatmap/ -- see the earthquake data set for 1.3 million points.  You can tweak all sorts of parameters live there.  @cdeepakroy and I were just discussing adding something to the annotation spec to support this as a first-class output.

**Comment by manthey** [comment]
This was added in #337.
