### ISSUE TITLE
Local failure building tests -- test "web_client_HistomicsTK_annotations" does not exist

### ISSUE THREAD

**Issue by neal-siekierski** [DigitalSlideArchive/HistomicsTK#316]
@jbeezley: @cdeepakroy and I get the error below when trying to build the tests on master. Clearly Travis has no problem with it, though. I get this error with a new build directory for Girder, and the particular revisions 6a7d593 and girder/girder@7b4022b. With `git bisect` I was able to locate bab64d8 as the first commit that causes the test build to fail.

```
-- Including plugin.cmake from "HistomicsTK"
CMake Error at plugins/HistomicsTK/plugin.cmake:100 (set_property):
  set_property given TEST names that do not exist:

    web_client_HistomicsTK_annotations

Call Stack (most recent call first):
  tests/CMakeLists.txt:111 (include)
  tests/CMakeLists.txt:123 (_add_plugin)


-- Configuring incomplete, errors occurred!
```

**Comment by manthey** [comment]
Can you ensure you are on the latest version of Girder master and see if the error still occurs?

**Comment by jbeezley** [comment]
That's strange, I'm not seeing an error at those revisions.  What version of cmake are you using?  Also, what is the output of `ctest -N`?

**Comment by cdeepakroy** [comment]
I am getting the same error as well on my machine.

The error occurs at the cmake configuration stage in `ccmake`. So can't run ctest as the tests dont even get generated at this stage.

My cmake version is 3.7.1 and i am on Ubuntu 14.04 LTS

**Comment by jbeezley** [comment]
I'm using cmake 3.7.2 on Ubuntu 16.04.  What if you comment out the `set_property` call?  Can you get through the configuration and run `ctest -N`?

**Comment by neal-siekierski** [comment]
The problem seems to be tied to the `BUILD_JAVASCRIPT_TESTS` option. If I set that to `OFF`, as I'd been doing, the error occurs; otherwise it doesn't. Looking into it a little more, `add_web_client_test` in `tests/JavascriptTests.cmake` in girder only adds the test of `BUILD_JAVASCRIPT_TESTS` is enabled. So the `set_property` call needs to somehow be made conditional on `BUILD_JAVASCRIPT_TESTS`.

**Comment by cdeepakroy** [comment]
Yes i confirm that it occurs in `ccmake` only if we set `BUILD_JAVASCRIPT_TESTS=OFF`.
