### ISSUE TITLE
UI error with NucleiClassification CLI

### ISSUE THREAD

**Issue by cdeepakroy** [DigitalSlideArchive/HistomicsTK#343]
When i try to apply the [Nuclei Classification CLI](https://github.com/DigitalSlideArchive/HistomicsTK/tree/master/server/NucleiClassification) on an image, as soon as i hit the submit button it throws an error in the developer tools console saying

```
Bad Request {"message": "No ID parameter passed: inputNucleiAnnotationFile_girderFileId", 
"type": "rest"}
```
Below is the screenshot

![ui_bug_classification](https://cloud.githubusercontent.com/assets/1923534/26496068/000a1d14-41f4-11e7-84cd-07ec6bd91313.png)

However, the CLI runs successfully when i directly call the REST end point through the swagger API by providing the item IDs of all the files needed by the CLI.

To help replicate this error, I have put some test data (input model file, feature file, and annotation file) in my [public folder](http://demo.kitware.com/histomicstk/#user/58b48d4d92ca9a000bdf783d/folder/58b48d4d92ca9a000bdf783e) in demo.kitware.com for this SVS [file](http://demo.kitware.com/histomicstk/#item/5925e3b092ca9a000b74a068) of LGG tumor type.

**Comment by cdeepakroy** [comment]
CC: @jbeezley @manthey

**Comment by manthey** [comment]
We are sending a parameter called inputNucleiAnnotationFile_girderItemId, but expecting inputNucleiAnnotationFile_girderFileId (Item versus File).

**Comment by manthey** [comment]
We could also make slicer_cli_web/server/rest_slicer_cli.py  handle either `_girderFileId` or `_girderItemId`, since this is where it is used.

**Comment by manthey** [comment]
Just changing to `_girderFileId` is insufficient, since the UI is sending an item ID and the cli is expecting a file ID.

**Comment by manthey** [comment]
I have an issue in slicer_cli_web for this: https://github.com/girder/slicer_cli_web/issues/45.  I'll have a PR there as soon as we decide if slicer_cli_web should handle items and files as two separate types or should equate a file with a Girder item.

**Comment by manthey** [comment]
Fixed in slicer_cli_web.
