### ISSUE TITLE
UI to download a ROI as a TIFF

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/HistomicsTK#352]
This would allow the user to select an ROI and then pick a magnification.  An estimate of the file size should be shown along with a download button.  If the output would require a BigTIFF (or, simplistically, has more than a gigapixel of data), don't allow a download.

The region endpoint can do the bulk of the work, but current is probably limited to png and jpeg.

**Comment by manthey** [comment]
@Pierre-Assemat made a branch called `download-button-ROI` which has an initial implementation which downloads the current window at the current window's resolution.

**Comment by Pierre-Assemat** [comment]
To select a ROI could we use the same tool than it used to draw annotation : like draw a rectangle then choose a magnification, show the size of the file ?

**Comment by manthey** [comment]
Yes.  It might be nice to have both the current option and a second button that would let you select the area.  The current button could be relabeled "Download View", and then add a second button which would be "Download Area"..  After drawing the rectangle, we could show a dialog with a choice of magnifications, the output width, height, total number of pixels, and estimated file size, and a Download and Cancel button.

**Comment by Pierre-Assemat** [comment]
I have few questions to clarify expectations :
- What is the best for the client: select magnification or zoom level ?
- What are the alterable parameters (Magnification/Zoom and Format are the only ones for now) ?
- How can I get corrects value of compression ratio for these different format (JPEG, PNG, and TIFF ) and the constant in the size file calculation ?
- Which is the default format ? 
- Do we need some verification test ?

**Comment by manthey** [comment]
- Magnification is best.
- Magnification and format for now.
- We'll have to make a few files and see if what sort of compression ratio we get.  We'll try a few different typical files.
- @dgutman originally asked for TIFF.  He can say if he'd prefer the default to be PNG or JPEG instead.
- We need to add tests once we get the the feature working.  Tests can be complicated, so perhaps ask @jbeezley while he is still physically around to give you an introduction to them.

**Comment by Pierre-Assemat** [comment]
I noticed different bug on this PR, without be detected by Travis CI tests, but I don't know the origin of this bugs : 

- I can't open an image 
![screenshot from 2017-10-05 12-20-43](https://user-images.githubusercontent.com/29961430/31238330-a5f85af2-a9c7-11e7-87eb-eb6ce52c9fce.png)
It's weird because the test : `web_client_HistomicsTK.annotations` try to open images and is passing on Travis but not on my local environment.

- The rendering of the image doesn't update very well, when I zoom into the image and zoom back after, all the side part, that should become blank still show the image, and this is worse when I put some annotations because it multiply them each time I try to move into the image or change the zoom.

I tried to see what could cause this kind of failure, but I'm a little bit confused

**Comment by manthey** [comment]
What other plugins do you have turned on?  I assume you rebuilt the Girder client and made sure that the browser was reloaded.  Have you updated Girder?  If not, perhaps you need to.  If so, are all of your npm packages up to date?

**Comment by jbeezley** [comment]
I think both of the issues are caused by recent changes to histomicstk that rely on updated girder and large_image.  Try updating them and rebuilding.

**Comment by Pierre-Assemat** [comment]
I think you're right, the 'open image' failure come from the merge from master into the branch. 
To update this plugins what I need to do ?

**Comment by jbeezley** [comment]
Run `git pull` in the main girder directory.  Then go into external plugins that you have installed `cd plugins/large_image` for example, and run `git pull` there as well.  You may also need to update `slicer_cli_web`.  With the current setup (this may change) when the tests run on travis, it is using the latest versions of everything.

**Comment by Pierre-Assemat** [comment]
Thank you, I will pull new changes of girder and large_image and see if it fix these issues

**Comment by Pierre-Assemat** [comment]
It works well now, thank you @manthey and @jbeezley 

One last thing, I will try to complete this PR as soon as possible, if you have some time to review it, I would appreciate. I don't know what is still missing and if the way it work fit to your expectations
