### ISSUE TITLE
Screen blanks with too many annotations

### ISSUE THREAD

**Issue by cooperlab** [DigitalSlideArchive/HistomicsTK#389]
The slide viewer screen will go blank when too many annotations are made visible (15 in our test case). This creates an issue for annotating large regions, where we need to see what has already been marked.

**Comment by jbeezley** [comment]
This is probably related to having too many GL contexts.  I think the solution is to draw annotations in a single layer.  It will take a bit of refactoring to accomplish.

**Comment by cooperlab** [comment]
It would be nice to have the annotations live in groups/layers similar to the image analysis annotations. That way we could turn all on/off with a single click, or adjust display parameters like color, fill, etc.

**Comment by manthey** [comment]
The fix will move the annotations to a single geojs layer; they will still be in separate features, so can still be turned on and off by annotation as they are now.

**Comment by manthey** [comment]
Fixed in https://github.com/girder/large_image/pull/214.
