### ISSUE TITLE
Switch from romanesco to girder_worker

### ISSUE THREAD

**Issue by cdeepakroy** [DigitalSlideArchive/HistomicsTK#39]
@brianhelba [.travis.yml](https://github.com/DigitalSlideArchive/HistomicsTK/blob/master/.travis.yml#L25) needs to be updated to switch from romanesco to girder_worker

**Comment by brianhelba** [comment]
@manthey Can you convert all of this plugin to use ``girder-worker`` instead of ``romanesco``.

You can do this here in HistomicsTK after you finish the same task in ``large_image``.

**Comment by manthey** [comment]
It looks like this needs to install some dependencies: openslide-python, scikit-learn, and nimfa from pip, and python-skimage from apt-get.  Versions appear important -- when I've installed all of these and try to process an image, I get an exception `fromstring() has been removed. Please call frombytes() instead`.  I think this means that some module wants an earlier version PILLOW.

**Comment by cdeepakroy** [comment]
@manthey All dependencies based on c libraries are in the [requirements_c.txt](https://github.com/DigitalSlideArchive/HistomicsTK/blob/master/requirements_c.txt) which is where nimfa should go i think.  All dependencies that are not based on c libraries go in [requirements.txt](https://github.com/DigitalSlideArchive/HistomicsTK/blob/master/requirements.txt). I had to do this separation because ReadTheDocs (that we use to auto-generate documentation) doesn't work if install_requires in setup.py as c-dependent libraries. I add the dependencies within requirements_c.txt into install_requires in [setup.py](https://github.com/DigitalSlideArchive/HistomicsTK/blob/master/setup.py#L34) only if `python setup.py install` is not run on ReadTheDocs.  This seems very convoluted. I will there was a better way to do this.

Also, .travis.yml should pip install this as i have pointed out in this [issue](https://github.com/DigitalSlideArchive/HistomicsTK/issues/19).

For openslide i guess we also have to do "apt-get install openslide-tools" as mentioned in this webpage. Dont know if we should
