### ISSUE TITLE
Annotations cannot be downloaded

### ISSUE THREAD

**Issue by cooperlab** [DigitalSlideArchive/HistomicsTK#392]
Clicking the download icon next to an annotation generates a "Failed - Needs authorization" error in Chrome and "File not found" error in Firefox.

**Comment by manthey** [comment]
This will be fixed by https://github.com/girder/large_image/pull/215.

**Comment by manthey** [comment]
I'll wait until we have confirmation from the Emory deployment before closing this, but I believe it is now fixed.

**Comment by manthey** [comment]
This was fixed in https://github.com/girder/large_image/pull/215.
