### ISSUE TITLE
Group download of annotations

### ISSUE THREAD

**Issue by cooperlab** [DigitalSlideArchive/HistomicsTK#393]
Ability to download all annotations for a slide or dataset (not one-by-one).

**Comment by jbeezley** [comment]
To do this, we will need to add an endpoint to large_image.  I'm thinking something like `/annotation/download?image=<id>` that generates a zip file similar to how the `/folder/<id>/download` endpoint works.  We can add additional filters to the endpoint later if necessary.

Would a zip file containing json files for each annotation work for you?  There is also the question of how the annotation files should be named in the zip file.  The annotation name is optional and not necessarily unique.  The annotation id is rather opaque to the user.  Maybe something like this: `<item name>_<item_id>/<annotation name>_<annotation id>.json`?

**Comment by kheffah** [comment]
@jbeezley  If I may give an opinion, I agree to everything you suggested, including the mechanism of download. Like you mentioned, adding the ability to filter by certain properties would also be great.

**Comment by manthey** [comment]
https://github.com/girder/large_image/pull/305 added an endpoint for downloading all of the annotations for an item.  As per this issue, a further refinement would be to add filtering or limiting to the process.  The `annotation/item/{id}` endpoint gets all annotations that the user has permissions to access and returns a json list, each of which has complete annotation information.

**Comment by manthey** [comment]
As mentioned, this was added in large_image.  Reopen (or open a new issue) if this is insufficient.
