### ISSUE TITLE
 Group members can delete each others' annotations 

### ISSUE THREAD

**Issue by kheffah** [DigitalSlideArchive/HistomicsTK#411]
It seems that individual members of a group that is part of the same project can delete each other's annotations. If a user clicks on the 'x' symbol on an annotation document (for example, by error due to a lagging internet connection), that could potentially delete all 50 annotations in that document created by another user!

I think the ideal solution would be to be able to turn on and off the "God mode". There's probably an easy way to do this: only allowing the "owners" of a group to be able to delete other people's annotations, the rest being able to view/edit their annotations only.

**Comment by jbeezley** [comment]
For the most part, this is resolved by #415.  It
* Adds a confirmation dialog when deleting annotations
* Removes the "delete annotation" button from regular (non-admin) users

It does not implement toggling god mode.  If that is still desired, feel free to add it to a new issue.
