### ISSUE TITLE
Need annotation documents to be visible by default

### ISSUE THREAD

**Issue by kheffah** [DigitalSlideArchive/HistomicsTK#419]
It's very tedious to click on the "eye" icon every time a slide is opened. This is especially important for review of slides with numerous annotations.
![screenshot from 2017-11-22 22-58-58](https://user-images.githubusercontent.com/22067552/33158542-c3fb6670-cfd8-11e7-97f3-9f28b8a12b45.png)

**Comment by jbeezley** [comment]
This is pretty easy to do.  Would it be better to show all be default or add a "Show all" button?

**Comment by kheffah** [comment]
@jbeezley I think it would be better to have a "show all" button, if possible. This way it easy to toggle on-and-off, and also makes it faster to initially load the slide without having to load all the boundaries at the same time.

**Comment by kheffah** [comment]
Is there an estimate of when this feature would be available. I think this is one of the more important things to have especially as expert reviewers have already started looking through people's annotations. Thank you for the support.
