### ISSUE TITLE
Fetched annotations don't include annotation name

### ISSUE THREAD

**Issue by kheffah** [DigitalSlideArchive/HistomicsTK#425]
When annotation documents are fetched, the individual annotations contain all important information *EXCEPT* for the annotation name. This is an important thing to fix as the annotation label does *not* substitute for it (and is, in fact, is optional). What this means is that I have tens of annotations from various users whose name (indicating their tissue class / important medical information) is unknown.
![screenshot from 2017-11-27 02-19-39](https://user-images.githubusercontent.com/22067552/33255183-5bf53e76-d31a-11e7-9596-3d8d2435ac6a.png)

**Comment by kheffah** [comment]
@manthey The name of the individual annotations is not necessarily the same as the name of the annotation group. Each individual annotation is given a name and a label in the UI, and multiple annotations are save together under a common annotation document, which has a name of its own. 
![annotname](https://user-images.githubusercontent.com/22067552/33281453-52179daa-d373-11e7-8556-4f4a495d64c8.png)
![annotname2](https://user-images.githubusercontent.com/22067552/33281454-52276c62-d373-11e7-82c5-873719631861.png)
![annotname3](https://user-images.githubusercontent.com/22067552/33281455-523cb68a-d373-11e7-8743-b1eccd0e302f.png)
![annotname4](https://user-images.githubusercontent.com/22067552/33281456-526b6c82-d373-11e7-846d-c36a9f0cb435.png)

**Comment by kheffah** [comment]
@manthey In this case, the individual annotations are all called "Mostly_Tumor", but there are many cases where the individual annotations are heterogeneous ("Mostly_Tumor", "Necrosis_or_Debris", "Mostly_Lymphocytic_Infiltrate" all in one annotation document). The UI says the label is "optional" while the name is needed, so some people did not even include a label ... That is, even though the label is what gets fetched and the name disappears somewhere!

**Comment by manthey** [comment]
The name in that dialog is the name for the group of style properties, and, pedantically, wasn't the name of any annotation.  We can change things so that the style group's name is stored that with the annotation (though the original intent was that label would be used if that was desired).

**Comment by kheffah** [comment]
> We can change things so that the style group's name is stored that with the annotation 

@manthey Yes please, that would be needed. The fact that the label is "optional" yet the style property shows on the right falsely indicates to users (myself and others included) that these styles are saved with the annotations, and that the label was just for display purposes (how it shows on the screen if I choose to show the label with the boundaries on screen). Is there any place where the style groups are linked to individual annotations in the current database? i.e. Is there any way for me to retrospectively find the annotation styles for the users that did not include labels?

**Comment by manthey** [comment]
The style group name isn't stored anywhere except in your local browser.  If each style group is distinct, you could find any annotation that has a particular set of styles and regroup them based on that (but you would have to correspond that group to the name manually).

Currently we set the style groups in the browser, but each browser has them configured separately.  We could add a default set for HistomicsTK (possibly just storing them in the config file or in a setting in Girder) so that they would be the same across multiple browsers (though that can be done as a separate issue).

**Comment by cooperlab** [comment]
@kheffah you probably need to issue an urgent alert to users on the annotation slack.

**Comment by manthey** [comment]
Assuming that each style group has something distinct about the style, we can reconstruct which group it was in from the data associated with the annotations.

**Comment by kheffah** [comment]
@manthey Thank you for taking care of this. Sorry it's such an urgent request. As you said, there are certain metadata (specifically, the boundary color and -sometimes- the document name) that can be used to retrospectively reconstruct the style group for the annotations missing labels, which is exactly what I will do. Thanks for the suggestion.

**Comment by kheffah** [comment]
@cooperlab Yes, I already did, Thanks!

**Comment by kheffah** [comment]
Closed because PR #426 is merged.
