### ISSUE TITLE
Disappearing work collections in HTK application

### ISSUE THREAD

**Issue by kheffah** [DigitalSlideArchive/HistomicsTK#437]
This is a low-priority, but strange bug. Sometimes the collections are missing from the drop-down menu of the HTK application after login, for no apparent reason. They remain so for a while, until after a few minutes (or perhaps after refreshing the page?) they re-appear. In this case, the "BRCA_Analysis" collection (along with many others) was missing and then just re-appeared without clear triggers.
<img width="1775" alt="screen shot 2017-12-13 at 4 16 38 pm" src="https://user-images.githubusercontent.com/22067552/33963161-fcea0686-e021-11e7-9099-c9779a8cbe3d.png">
<img width="1779" alt="screen shot 2017-12-13 at 4 18 19 pm" src="https://user-images.githubusercontent.com/22067552/33963169-073093a8-e022-11e7-8b3b-8b4f1349ba93.png">

**Comment by manthey** [comment]
Any additional information about when it occurs would be useful.  For instance, when there are collections missing, can you open the browser's developer tools, click Open Image again, and then copy the information for the network request that gets the collection list (the curl variant is probably the most useful, if you are using Chrome).  I'd like to see what the request has for the url and the Girder-Token header.

**Comment by kheffah** [comment]
@manthey Thanks, I will get the Curl variant the next time I see this issue.

**Comment by manthey** [comment]
We haven't had a report of this issue in two years.  I'll close this.  Please reopen if you see it again.
