### ISSUE TITLE
Disappearing annotations

### ISSUE THREAD

**Issue by kheffah** [DigitalSlideArchive/HistomicsTK#443]
After the incorporation of new features (editable individual annotations and highlighting annotations when mouse hovered over boundary), at least 4 users reported disappearing annotations (i.e. not saved). It did not happen with me, so I didn't get the chance to get the curl variant or other more useful metrics, but I will try.

**Comment by kheffah** [comment]
If it's almost a necessity that the interface would be slower when interactive highlighting of annotations occurs, I suggest adding a checkbox "Interactive Mode", which toggles this on- and off-, if possible.

**Comment by manthey** [comment]
Is there any more data on when they disappeared?  For instance, after initially drawing the annotation versus editing an existing annotation?

**Comment by kheffah** [comment]
Here is the account from one of the users, I will ask others for more description:

_"while annotating the slide disappeared totally and then refreshed the page many times then it loaded and annotation was not saved that happened with one slide.. other one annotation disappeared completely exactly half of it.."_

**Comment by kheffah** [comment]
Account from another user:

_"After editing more than 10 annotations in a group, some disappear and others remain."_

**Comment by kheffah** [comment]
Another user:

_"I opened the website, then did annotations in three new folders, then I left the slide page open for some time without annotating. When I came back to do some more, I found that all the annotations in these three folders are gone. Although the old annotations remained the same. This was one time.
The other 2 times I don't remember exactly but it was something like that. I left the page open for some time then I found them gone. Also when I click refresh they don't appear.

N.B.: I'm using Mozilla Firefox web browser"_

**Comment by jbeezley** [comment]
I can try to do some more testing here.  Do you have a database dump somewhere?  It would be interesting to see what the histories are on these... I.e. are the annotations appearing and then being overwritten with old data?

Just to make sure, people aren't editing the same annotations at the same time are they?

**Comment by manthey** [comment]
I think I've just reproduced it.  It has to do with switching to another tab and then switching back after a while, I think.

**Comment by kheffah** [comment]
@jbeezley I don't have a dump, unfortunately, but I don't think it would be very helpful anyways because people are working on new annotations, not editing old ones. Also, it's very unlikely that people are working on the same annotation because:
1- They are assigned different slides.
2- Even if they did try to edit the same annotation, they cannot because the permissions only allow the annotation owner to see the annotation document components and to edit it.

**Comment by kheffah** [comment]
@manthey This makes sense, and seems to be consistent with some of the user reports.

**Comment by manthey** [comment]
Knowing the problem, I hope to have a fix soon.  As a work around, when refocusing the window, click a different annotation and then click the annotation that is to be edited.

**Comment by kheffah** [comment]
@manthey Thank you for the quick response, I appreciate it. May I ask what do you mean by "refocusing the window"? Do you mean moving to a different area of slides? Or ..?

**Comment by manthey** [comment]
The problem occurs when either you switch tabs in the browser and switch back.  After switching back to the HistomicsTK tab, switching which annotation is being edited and then switching back to the one you actually want to edit will work around the problem.

**Comment by kheffah** [comment]
@manthey Got it, will relay this to the users as a temporary workaround. Thank you!

**Comment by kheffah** [comment]
@manthey I got this feedback from a user today, not sure if she accidentally did something else that cause the even stream to disconnect:

_"They were removed while I was working. I haven't closed any tabs or left the laptop for any reason."_

**Comment by manthey** [comment]
I pushed new docker images with the fix in PR #445.  @dgutman should update those soon; if there is an issue after that, we'll look into it then.

**Comment by kheffah** [comment]
Thank you so much, that's great to hear! Will let you know.
