### ISSUE TITLE
Annotation creation/update date only stored for documents, not individual annotations

### ISSUE THREAD

**Issue by kheffah** [DigitalSlideArchive/HistomicsTK#444]
Now that individual annotations can be edited within an annotation document, it naturally follows that individual annotations should have their own "independence" in terms of creation/update date and time. This would also set the stage for storing version of the annotations. This is relevant because the time of annotation creation carries information that is useful when deciding on the preferred overlay order when post-processing (annotations -> masks) is done.

**Comment by manthey** [comment]
Since we use a mongo id for annotation elements, and the mongo id contains the date of creation, you could use that value to determine the creation time of the element.

**Comment by kheffah** [comment]
@manthey I see, that's great! Thank for pointing this out to me.

**Comment by kheffah** [comment]
Closed, because can be deduced from Mongo ID.
