### ISSUE TITLE
Positive Pixel Count plugin expects user input for "output parameters"

### ISSUE THREAD

**Issue by yliu7366** [DigitalSlideArchive/HistomicsTK#456]
Hi, 

Please see the screenshot below. HistomicsTK is asking user input for output parameters in the positive pixel count plugin. I am confused as if these parameters are really 'output' parameters then there's no need to manually input values for them, right?

For now I can just enter 0 for all of them in order to submit the job but it might be something needs to be fixed.

Thanks,
 
<img width="307" alt="screen shot 2018-02-02 at 2 17 16 pm" src="https://user-images.githubusercontent.com/30328162/35750736-fb756ea6-0823-11e8-99a5-e1300b35a7a5.png">

**Comment by jbeezley** [comment]
I think we solved this issue in https://github.com/girder/slicer_cli_web/pull/43.  We should probably try to get that merged in.

**Comment by yliu7366** [comment]
May I ask when will the fix be merged in?

**Comment by jbeezley** [comment]
I resolved all the conflicts with master.  There are still testing errors, but they are unrelated to my changes.  It could be reviewed as is, but @cdeepakroy seemed to indicate that we are moving to taking a different approach with output files.  If that is the case, then these changes probably don't make sense.  I'll leave it to @cdeepakroy if he thinks we should go ahead with it.

**Comment by manthey** [comment]
https://github.com/girder/slicer_cli_web/pull/43 was merged some time ago.
