### ISSUE TITLE
Add slidebar for filled annotation transparency

### ISSUE THREAD

**Issue by kheffah** [DigitalSlideArchive/HistomicsTK#458]
My group is using HTK to review mask overlays, so we are using the "fillColor" of annotations. However, the filled annotations are too opaque to show underlying structures, so we need some sort of a sliding bar to control displayed "alpha" (transparency) of filled annotations. The temporary "hacky" workaround we are using is by hovering the mouse over the annotation name on the right, which decreases the opacity of all annotations except the one the mouse is overlayed on. (see attached screenshots for pre- and post- mouse hovering)
![screenshot from 2018-02-11 19-02-25](https://user-images.githubusercontent.com/22067552/36080457-5bc5b540-0f5e-11e8-8a4b-1cc20f9c162a.png)
![screenshot from 2018-02-11 19-02-42](https://user-images.githubusercontent.com/22067552/36080458-5bd5f1da-0f5e-11e8-8c36-3c9c7a44a097.png)

**Comment by manthey** [comment]
When you create or edit the style on an individual annotation or annotation group you can set the opacity as part of the fill color.  I assume you don't want to create the annotations with a different opacity, but want an overall opacity slider.

**Comment by kheffah** [comment]
Thanks David for the response. I missed that the fill color actually encodes alpha information (I was assigning fill color automatically as the same as boundary color). Still, our need is not a fixed alpha but the ability to toggle between opaque and translucent for efficient review of results, so a sliding bar is really the ideal solution, in my opinion.

**Comment by cooperlab** [comment]
The alpha level shown above is a good default. That would maybe be an easier temporary fix.

**Comment by kheffah** [comment]
@cooperlab Yes, I've already taken @manthey 's advice and change the default displayed alpha level 0.5 for review.
