### ISSUE TITLE
Add checkbox to toggle interactive mode

### ISSUE THREAD

**Issue by kheffah** [DigitalSlideArchive/HistomicsTK#459]
Since the new changes were pulled, specifically the highlighting of individual annotations when mouse is hovered over boundary and vice versa, panning a heavily-annotated slide became slower. This is especially evident with extensive annotations, where any slight mouse movement inevitably crosses some boundary, even if the original intention is just to pan the slide. I suggest adding a checkbox for interactive_mode, where default is True and can be turned off by user.

**Comment by manthey** [comment]
@kheffah I have some ideas on how this could also be sped up (though we'll still add a checkbox).  Do you have a specific example item with lots of annotations that I can use as a good test case for optimization?

**Comment by kheffah** [comment]
@manthey Yes, I have an example. I wonder how to share it with you, do you need the slide girder id? If so, let me know and I'll share it to your email.
