### ISSUE TITLE
auto-naming in analysis modules?

### ISSUE THREAD

**Issue by yliu7366** [DigitalSlideArchive/HistomicsTK#462]
Hi, would it be possible to automatically suggest output file names and locations based on input image name and location? For example, in the Color Deconvolution module, if the input filename is test.tiff, then the module automatically suggest test_stain1.tiff, test_stain2.tiff, and test_stain3.tiff as output filenames instead of letting user to open file dialog multiple times to set filenames, these output files could be conveniently saved at the same location as the input file. This will make HistomicsTK a lot easier to use. Thanks!

**Comment by dgutman** [comment]
We actually added that..I agree it's tedious.. I think it's being reviewed
...

**Comment by manthey** [comment]
This was added some time ago.
