### ISSUE TITLE
editing label programatically is not allowed

### ISSUE THREAD

**Issue by kheffah** [DigitalSlideArchive/HistomicsTK#464]
When I try to edit the label of individual annotations inside an annotation document, I get the "schema not followed" error. All other properties are OK, except label. I am using something like:
`gc.put("/annotation/" + annotdoc["_id"], json= annotdoc_new)`
I am able to edit lineColor, fillColor, and group, but not the "label" property. I assume it clashes with some internal variable name (?) or perhaps some forbidden keyword somewhere.

**Comment by kheffah** [comment]
If it helps, I *am* able to set the "label" property when pushing brand new annotation documents using `gc.post`; it's only when I try to edit an existing document using `gc.put` that I get this error.

**Comment by manthey** [comment]
How did you specify the label?  The label is actually a dictionary of information, where `value` is required :
```
"label": {
  "value": <the text of the label>,
  "visibility": <one of "hidden", "always", "onhover">,
  "fontSize": <number>,
  "color": <css color value of the form #rgb, #rrggbb, rgb(r, g, b), or rgba(r, g, b, a)>
}
```

I just tested with "label: {"value": "test"} on one element, and it worked for me.

**Comment by kheffah** [comment]
Got it. Now it works. Thank you!
