### ISSUE TITLE
Scale bar

### ISSUE THREAD

**Issue by cooperlab** [DigitalSlideArchive/HistomicsTK#468]
Should snap to integral values depending on zoom factor. Should scale with zoom between factors.

**Comment by manthey** [comment]
It will take a while to get various PRs merged in that will show this, but I have it working: 
![image](https://user-images.githubusercontent.com/8781639/37599879-34ba6698-2b5c-11e8-8edd-e066718f6568.png)
It currently snaps to even numbers: 1, 1.5, 2, 3, 5, 8; and to appropriate powers of 10.  If you want different possible even values, it is easy to change.

**Comment by cooperlab** [comment]
Looks great!

**Comment by manthey** [comment]
Resolved by PR #492.
