### ISSUE TITLE
Menu bar overflow bug

### ISSUE THREAD

**Issue by zachmullen** [DigitalSlideArchive/HistomicsTK#499]
![screen shot 2018-04-16 at 10 14 38 am](https://user-images.githubusercontent.com/555959/38814641-f4fc755e-415f-11e8-8fbc-5fb30c59f5ea.png)

I saw this on demo.kitware.com, I didn't test with latest master.

**Comment by jbeezley** [comment]
This was fixed in #494.

**Comment by zachmullen** [comment]
When will this get deployed to demo.kitware.com? Is that automated or manual?

**Comment by manthey** [comment]
Deployment to demo.kitware.com is manual, usually after a significant feature has been added and I think it is stable enough (so subject to my whim or someone prodding me).
