### ISSUE TITLE
Hover highlighting fails for large numbers of objects

### ISSUE THREAD

**Issue by cooperlab** [DigitalSlideArchive/HistomicsTK#512]
@jbeezley when hovering on an annotation in the image viewport, the corresponding element in the "Draw" box will highlight but may not be visible due to the length of the list (when there are a large number of elements). This makes it difficult to delete or to modify elements.

One solution would be to move the list position automatically when the element is out of view to bring it into the visible portion of the list.

**Comment by cooperlab** [comment]
Being able to raise a delete dialog by hovering then right-click would be easiest for people doing extensive annotation.

**Comment by manthey** [comment]
We added the delete dialog from the right click menu some time ago.
