### ISSUE TITLE
Need to have zoom beyond 20x

### ISSUE THREAD

**Issue by kheffah** [DigitalSlideArchive/HistomicsTK#520]
For nucleus annotation, it is often needed to zoom to very high magnifications to be able to make a good histologic judgement of what class it belongs to. It's OK if the image gets pixelated a bit, but some kind of "hyper-zoom" functionality would be preferred.

**Comment by manthey** [comment]
We can zoom arbitrarily far.  Currently we restrict the zoom to 1 image pixel per display pixel.  Should we allow a fixed ratio more?  Or a fixed maximum size in microns?  Or something else?

**Comment by kheffah** [comment]
I think maybe the maximum should be 2 display pixels per image pixel. That way way even if a slide is only scanned at 20x, we can zoom to 30x or 40x to verify nucleus identity. @manthey would that be feasible? Thanks!

**Comment by cooperlab** [comment]
I think this 2-times limit is what most of the industry viewers use. It's fairly obvious when you've gone past the optical magnification into digital zoom.

**Comment by manthey** [comment]
I've got a PR (#522) that allows zooming more.  It is set to allow a maximum 2x2 display pixels per image pixel.  The Zoom Widget reflects where it is above native resolution, for example:
![image](https://user-images.githubusercontent.com/8781639/43724612-63696f50-9968-11e8-9d44-9da6f27ccdb9.png)
This image is 20x, so 40x is an over-zoomed size.

**Comment by cooperlab** [comment]
Great design @manthey
