### ISSUE TITLE
Need hotkey for annotation editing and/or deletion

### ISSUE THREAD

**Issue by kheffah** [DigitalSlideArchive/HistomicsTK#521]
for example, holding shift+left click on an annotation should immediately pop up the the "edit annotation" tab. Right now, you have to click "interactive", then hover over annotation to find where it is, then scroll to its metadata location on the right tab, then click on "edit". That a lot of work to just edit one annotation, in my opinion, especially when you want to edit many annotations.

**Comment by cooperlab** [comment]
We discussed this on the last call with @manthey and @jbeezley.

There was some question about how to display the list of possible styles to assign the annotation to (this is basically how we change the class).

**Comment by kheffah** [comment]
I see, yeah it will need a bit of thinking.

**Comment by kheffah** [comment]
Addressed by new context menu.
