### ISSUE TITLE
Context menu "overflows" over edge of screen

### ISSUE THREAD

**Issue by kheffah** [DigitalSlideArchive/HistomicsTK#531]
When close to edge, context menu should be centered instead overflowing beyond screen edge (which necessitates zooming out, panning, then right clicking making the process of changing or deleting annotations slower for high-volume projects).

![image](https://user-images.githubusercontent.com/22067552/45065879-944ecb00-b089-11e8-916f-2c150850ed14.png)

**Comment by kheffah** [comment]
Along the same lines, the styles listed in context menu should preferably be listed in order of number of elements (most to least) not alphabetically.

**Comment by jbeezley** [comment]
Fixed by #548
