### ISSUE TITLE
Context menu pops up for wrong object

### ISSUE THREAD

**Issue by kheffah** [DigitalSlideArchive/HistomicsTK#534]
Sometimes when I right click inside an annotation, the context menu pops up for the outside object not the innermost one. Int he example below, I right click on a nucleus, but the context menu pops up for the FOV instead. The correct behavior is for it to pop up for the innermost object.

![image](https://user-images.githubusercontent.com/22067552/45066275-a3cf1380-b08b-11e8-8de3-04c11d92f27e.png)

**Comment by jbeezley** [comment]
Fixed by #550
