### ISSUE TITLE
Browser "hung up" when I press "ESC" while dragging mouse to create annotation

### ISSUE THREAD

**Issue by kheffah** [DigitalSlideArchive/HistomicsTK#535]
Very often, I would start dragging the mouse to create an annotation, say a rectangle, then I decide I made a mistake and press escape ("esc") to quit it and start a new one. Almost every time I do this, the browser gets completely "hung up", sometimes to the point where I need to close the tab or refresh the page. I don't know what event gets triggered but this is definitely an undesirable behavior. Is this the correct way to stop an annotation midway if you made a mistake?

**Comment by jbeezley** [comment]
Escape is the right way to do it. I think I found the problem.  It will probably only happen when hitting escape while holding down the mouse button.  At least in my testing, hitting escape while drawing a rectangle with the "two clicks" method doesn't cause any issues.

**Comment by manthey** [comment]
I can reproduced that in the GeoJS library (hitting escape while dragging a rectangle), though I had to do it multiple times to cause the browser tab to hang.  I'll hunt down the bug there.

**Comment by jbeezley** [comment]
Ah, okay.  I didn't manage to make it occur in the geojs example.  I was assuming it had to do with how we retrigger draw mode.

**Comment by manthey** [comment]
I have a fix for this in https://github.com/OpenGeoscience/geojs/pull/923.

**Comment by manthey** [comment]
This is fixed in the latest docker builds.
