### ISSUE TITLE
Copying slides using UI does not copy annotations alongside

### ISSUE THREAD

**Issue by kheffah** [DigitalSlideArchive/HistomicsTK#536]
Using the DSA UI to copy an item (slide), does not also copy the annotations on that item. The only way I was able to do this earlier is by copying them separately using the python REST API, but the end user (and even the power user for many tasks) should be able to simply copy slides and all annotations on them using point and click.

![image](https://user-images.githubusercontent.com/22067552/45069127-f06d1b80-b098-11e8-8add-88a9a7299fd1.png)

**Comment by manthey** [comment]
@kheffah If you copy an item from another user (that you have permissions for, obviously), and you include the annotations, who should have permissions on the copied annotation?

I think the user who owns the destination folder where the item is copied should have write-permissions (since the item and hence the annotations are now in their folder).  Should we just add this?  Or should we restrict permissions to just that user?  Or convert any extant permissions to still exist but be read-only?

This is all easy to do in the code.  I'd like to pick the least surprising choice, so when we do this months from now we aren't puzzled.

**Comment by kheffah** [comment]
@manthey Thank you for your help and for taking my opinion. My opinion is that the first option makes most sense; I wouldn't copy the old permissions alongside. Instead, like you suggested, the user who owns the destination folder where the item is copied should have write-permissions (since the item and hence the annotations are now in their folder).

**Comment by manthey** [comment]
Great.  I should have a PR with the server side of this shortly.  After that I'll add it to the UI.  The copied annotations will have the same permissions as the copied item; this is simple and fairly clear.

**Comment by kheffah** [comment]
@manthey Wonderful! Thanks again!

**Comment by manthey** [comment]
@kheffah https://github.com/girder/large_image/pull/342 resolves this.  From the server side, `POST resource/copy`, `POST item/{id}/copy`, and `POST folder/{id}/copy` each take an additional boolean parameter of `copyAnnotations`.  From the UI, the pick menu has an additional option:
![image](https://user-images.githubusercontent.com/8781639/54621339-fd05ff80-4a3d-11e9-99a3-b0365c3e8564.png)
so you can choose whether to copy annotations or not. 

Note that there is no cleverness in the pick menu -- it doesn't check if anything you picked has annotations, it just passes the `copyAnnotations` flag to the endpoint if you choose that option, and lets the server figure it out.

**Comment by manthey** [comment]
Originally, we explicitly chose not to copy annotations with images.  Is that decision still sound?  I could refactor the PR for copying annotations to just always do so, which would make it much simpler (and remove the extra menu item).

Opinions?

**Comment by cooperlab** [comment]
At the time we didn't have a reason to copy annotations. I think that was the reasoning.

I think making the copy optional but true by default is the best choice. There may be cases where we want to copy things without the annotations, and deleting them would add another step.

**Comment by jbeezley** [comment]
My primary concern with the change as it exists now is that it unconditionally adds this menu option for anyone installing large_image.  If this could be moved to HistomicsTK or any other more project specific plugin, I would be fine with it.

**Comment by kheffah** [comment]
I'm with @cooperlab on that one. I think the ideal scenario is to make the annotations get copied by default. There maybe scenarios where we want to copy slides without annotations, although these would be much less common. I think this follows a similar reasoning as copying a folder; when the user copies a folder, it's presumed that the user wants to copy the folder along with all its contents. So overall my recommendation is:
- API -- keep the added boolean flag `copyAnnotations` but set its default value to true. 
- UI -- just keep just make "copy picked resources here" automatically copy annotations alongside and get rid of the "copy picked resource with annotations' option.

**Comment by manthey** [comment]
Sounds good.  I'll update the PR shortly.

**Comment by kheffah** [comment]
Thank you!!
