### ISSUE TITLE
Annotation permissions may be buggy?

### ISSUE THREAD

**Issue by kheffah** [DigitalSlideArchive/HistomicsTK#537]
I'm not sure I understand the annotation permissions and how they are inherited or set. I'm wonder whether there's a bug causing some the problems below? If possible, It would be wonderful to have this fixed so that users can work on a team on the annotations. 

Screenshot 1: Mo Tag is set to be able to view everything in collection and subfolders:

![image](https://user-images.githubusercontent.com/22067552/45070015-5cea1980-b09d-11e8-88d9-534c89c825cf.png)

Screenshot 2: Mo Tag can ONLY view slides but not annotations. I assume this means that permissions in collections when set using UI apply to items (slides) but not to annotations?

![image](https://user-images.githubusercontent.com/22067552/45070178-0df0b400-b09e-11e8-9ff0-e43f6ebe377f.png)

Screenshot 3: Indeed, when I go to any individual annotation within the collection, I don't see Mo Tag's name there are one of the people who have permission to view:

![image](https://user-images.githubusercontent.com/22067552/45070270-7a6bb300-b09e-11e8-9967-c4bfb40e7409.png)

Screenshot4: I add Mo Tag to the annotation, making sure he can view:

![image](https://user-images.githubusercontent.com/22067552/45070298-a2f3ad00-b09e-11e8-864f-6c0ac5f9c7b7.png)

Screenshot5: I log out, then log back in as MoTag. I can now see the annotation in the sidebar, but cannot actually view it! (Note this annotation contains 1000 polygons and is visible at this same magnification when I am logged in as the collection owner).

![image](https://user-images.githubusercontent.com/22067552/45070399-12699c80-b09f-11e8-8092-05abc15050d5.png)

Desired behavior is as follows:

- Annotations permissions can be set individually
- By default, any person can edit/delete their own annotations but not anyone else's.
- Collection owner or admin can set annotation permissions individually, including giving specific users ability to edit/delete other people's annotations. 

Thank you so much for your help in advance.

**Comment by kheffah** [comment]
Screenshot6: Turns out as soon as I changed the annotation permission for that annotation using the UI, it moved to a different group on is own (moved to "other") and all its polygons became invisible even to admin!! Not sure if its polygons we also deleted from the database but this means that changing the annotation permissions using the UI is dangerous and results in very unexpected behaviour. 

![image](https://user-images.githubusercontent.com/22067552/45070739-cc153d00-b0a0-11e8-981c-374fabab2296.png)

**Comment by kheffah** [comment]
Reopened because issue still exists. As MoTag, I am unable to view the annotations, and therefore as an admin I am unable to pre-assign annotations to different users.

**Comment by kheffah** [comment]
To clarify, he persistent issue is that a user who is listed as being able to "view" the annotations in a folder is unable to view them. I've only tried this for pre-existing annotations before the new update, but will try to post new annotations and see if this is also true prospectively.

**Comment by kheffah** [comment]
OK, I tested it on new annotations and the problem does **not** exist. So this bug only applies retrospectively to the annotations that were created before the pull request. Therefore it is a low priority bug IMO.

**Comment by kheffah** [comment]
@manthey @cooperlab  Sorry to bring this up again, but this issue keeps causing problems. Every time I add a new person to the project, they are unable to see any of the annotations that were previously added to the project. We need a systematic way to edit the permissions of all annotations in a folder from the UI (or at least from the API). This is becoming such a critical issue it is blocking progress in the project essentially (because every new recruit faces this problem and I'm unable to make them see the annotations).

**Comment by cooperlab** [comment]
@manthey this sounds like a high-priority issue.

@kheffah this issue was seemingly resolved before, or this is a persistent issue we never addressed?

**Comment by kheffah** [comment]
@cooperlab It was fixed, and we agreed during the weekly call to leave annotation permissions and folder permissions separate, which is exactly the case. So everything is as we agreed previously. My main problem is that when I add a new collaborator, he/she now cannot see the annotations because the annotation permissions were set to follow the original permissions of the folder, which did not include the new collaborator. A simple solution would just to include some functionality for modifying permissions of all annotations belonging to slides in a folder.

**Comment by kheffah** [comment]
I think I fixed the issue, though it would be nice (not sure if a high priority) to have some direct way to do this from the UI or API. My solution is to add the new member to the group, and to make sure the group has permission to view the annotations.

`
DESIRED_PERMISSIONS = """{
  "groups": [
    {
      "description": "User Group for Mohamed's Annotation Project",
      "flags": [],
      "id": "*****************",
      "level": 0,
      "name": "brcaAnnotators"
    }
  ],
  "users": [
    {
      "flags": [],
      "id": "*****************",
      "level": 2,
      "login": "************",
      "name": "admin admin"
    },
    {
      "flags": [],
      "id": "*****************",
      "level": 2,
      "login": "************",
      "name": "Mohamed Tageldin"
    },
    {
      "flags": [],
      "id": "*****************",
      "level": 1,
      "login": "************",
      "name": "david gutman"
    },
    {
      "flags": [],
      "id": "*****************",
      "level": 1,
      "login": "************",
      "name": "Lee Cooper"
    }
  ]
}"""

for sldno, sld_girderID in enumerate(sldidxs):
    
    print("Slide %d of %d: %s" % (sldno, N_SLIDES, sld_girderID))

    # get annotations for this slide
    slideAnnotations = gc.get('/annotation?itemId={}'.format(sld_girderID))
    
    # go through annotations and edit permissions
    for ann in slideAnnotations:
        ann_girderID = ann['_id']
        _ = gc.put('/annotation/%s/access?access=%s' % 
                 (ann_girderID, DESIRED_PERMISSIONS))

`

**Comment by cooperlab** [comment]
@kheffah I think groups are a good way to manage this - but like you said, would be nice to be able to manage this through the UI.

**Comment by kheffah** [comment]
Yes. Since this isn't technically a bug, I'm changing the label to enhancement.

**Comment by kheffah** [comment]
https://girder.readthedocs.io/en/stable/_modules/girder/constants.html
NONE = -1 READ = 0 WRITE = 1 ADMIN = 2 SITE_ADMIN = 100
