### ISSUE TITLE
Multiselect does not work when more than one annotation style is viewed simultaneously

### ISSUE THREAD

**Issue by kheffah** [DigitalSlideArchive/HistomicsTK#540]
Specifically, it becomes unreliable when making the right click to invoke the context menu. The problem disappears when only one annotation style (color/alpha/etc) is viewed.

**Comment by jbeezley** [comment]
I'm fairly certain this is caused by unexpected behavior related to #534.

**Comment by jbeezley** [comment]
Fixed by #550.
