### ISSUE TITLE
History becomes full of HistomicsTK pages

### ISSUE THREAD

**Issue by kheffah** [DigitalSlideArchive/HistomicsTK#547]
This is a minor issue, but I thought I'd bring it up anyways. It seems that when I browse histomicsTK that my history becomes completely engulfed by the server requests to get tiles and pan slides. This is on chrome. Is this a chrome issue (i.e. can easily be fixed in configurations), otherwise is it possible to somehow have these grouped together (eg slide-by-slide)?

![image](https://user-images.githubusercontent.com/22067552/45708310-0f66b580-bb4f-11e8-87bc-489c71b1e052.png)

**Comment by jbeezley** [comment]
Hmm...  [This line](https://github.com/DigitalSlideArchive/HistomicsTK/blob/master/web_client/views/body/ImageView.js#L369) was supposed to be preventing the pan events from saving to browser history.  The option is probably not being passed to the backbone route by some weird interaction with girder.  I can look into it.

**Comment by jbeezley** [comment]
After some digging around a bit, the behavior is as [expected](https://stackoverflow.com/a/12126658).  Holding down the back button shows that the history api is not saving the history state for all of the pan/zoom navigations.  It is only showing up in Chrome's history page.  The browser does not appear to expose any API for this page and always shows every url visited.

I think the only way to prevent this is to stop updating the url in response to panning/zooming the image.  This would mean reloading the page would not save the previous viewport.  We could still keep the ability to "bookmark" a view, but it would have to be through manually updating the url or via an alternate text box other than the url bar.

**Comment by sgratzl** [comment]
is this issue still valid? I played around with Chrome 77 and I don't see my history is growing anymore

**Comment by kheffah** [comment]
The issue seems no longer valid in Chrome 77. Like @sgratzl I also played around and confirmed it got fixed.
