### ISSUE TITLE
Error in importing histomicsTK on python 3.6.1

### ISSUE THREAD

**Issue by anilk991** [DigitalSlideArchive/HistomicsTK#551]
I get following message when I try to import histomicstk:

Python 3.6.1 (default, Sep 11 2018, 02:16:25) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import histomicstk
INFO:root:Created LRU Cache for 'tilesource' with 83 maximum size
INFO:root:Notice: Could not import MapnikTileSource
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anil/large_image/HistomicsTK/histomicstk/__init__.py", line 5, in <module>
    from . import utils  # must be imported before other packages
  File "/home/anil/large_image/HistomicsTK/histomicstk/utils/__init__.py", line 19, in <module>
    from .sample_pixels import sample_pixels  # must import after SimpleMask
  File "/home/anil/large_image/HistomicsTK/histomicstk/utils/sample_pixels.py", line 114
    print "Sampling could not identify any foreground regions."
                                                              ^
SyntaxError: Missing parentheses in call to 'print'

Is histomicstk a python 2 package?

**Comment by cdeepakroy** [comment]
Yes it is still not entirely Python 3 compatible. We are actively working on the port to Python 3 and we expect it to come soon.

**Comment by Tsakunelson** [comment]
I am having exactly the same issue as you @anilk991. Did you solve the problem?
![image](https://user-images.githubusercontent.com/17685437/52005133-f07e1580-2496-11e9-8348-8b593e01cb52.png)
I happens to be a MapnikTileSource dependency from the Mapnik package required by large_image. Any solutions to this issue? @cdeepakroy

**Comment by manthey** [comment]
You probably don't need to the mapnik tilesource -- it is for geospatial images, such as geotiff, netcdf.  The notice that it can't import is informative, rather than an error.  If you need to work with geospatial images, you can install mapnik and gdal, but if not you can safely ignore this.

**Comment by manthey** [comment]
We now explicitly test with Python 2.7, 3.5, and 3.6.
