### ISSUE TITLE
Problems running the client

### ISSUE THREAD

**Issue by luistelmocosta** [DigitalSlideArchive/HistomicsTK#558]
Good evening,
I would like to know how are you running the web client. I tried to run the app.js with node but I keep getting `Unexpected identified` errors. It seems that nodejs does not support ES6 and then I can't import Girder. 

What am I doing wrong?

Regards

**Comment by manthey** [comment]
The HistomicsTK web client is just a Girder 2.x plugin.  See the https://github.com/DigitalSlideArchive/HistomicsTK/blob/master/ansible/README.rst for various ways to install and run it.
