### ISSUE TITLE
Allow changing the color of all components of an annotation

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/HistomicsTK#562]
This would probably be added in the Edit Annotation dialog.

Expose styles for the entire annotation -- fill color, line color, line width.  If they are mixed, I'd imagine that the control would start blank.

**Comment by manthey** [comment]
This was mentioned again in today's meeting.

**Comment by sgratzl** [comment]
as far as I can see when I open the edit annotation dialog of a newly added annotation it looks like:

![image](https://user-images.githubusercontent.com/4129778/66397173-40f42e00-e9a9-11e9-9841-a2ce69442e41.png)

Thus, already allowing to reset the fill and line color.

am I missing something?

**Comment by manthey** [comment]
We should populate the line and fill colors with the existing colors if they are all the same.

We need to add line width as well.
