### ISSUE TITLE
Need to ask for confirmation before deleting annotation group, but not when deleting individual polygons

### ISSUE THREAD

**Issue by kheffah** [DigitalSlideArchive/HistomicsTK#578]
![image](https://user-images.githubusercontent.com/22067552/51431281-b0947400-1bf4-11e9-8679-de43a527dafb.png)

I think this is a fairly important enhancement given that recently a large collection of annotations diseappeared, likely due to accidental clicking by an admin (me?) on the "x" button causing tens of annotation polygons to be deleted. I would highly recommend that we pop up a warning to confirm deletion if the user clicks on the annotation (a group pf polygons), but not when the user clicks on the "x" beside any single polygon. We need to be able to quickly delete individual polygons (it's critical for my large-scale annotation project to correct hundreds of annotations) but we need to protect against accidental deletion of tens of polygons.

Thanks!

**Comment by dgutman** [comment]
We can also roll back changes if you really deleted anything important .

**Comment by kheffah** [comment]
@dgutman Thanks. Luckily I had backup this time so no problem. I'd always prefer a warning than look back through history and wonder what changed, especially cine the number of annotations is very large and complex (algorithm generated vs user generated vs corrections vs FOVs).

**Comment by manthey** [comment]
We do show a confirmation dialog before deleting an annotation group.  Are you sure you are on a recent version?  You can use the GET /api/v1/system/version?fromGit=true endpoint to see the exact versions that are being used.

**Comment by kheffah** [comment]
@manthey Thank you! My bad. I was under the impression I had back when  we did not yet show a confirmation and immediately assumed that the disappeared annotations (mentioned in issue #576 ) were caused by human error.
