### ISSUE TITLE
Enable pan at low-magnification

### ISSUE THREAD

**Issue by cooperlab** [DigitalSlideArchive/HistomicsTK#581]
It is not possible to directly zoom into regions that fall under the annotation menus.

Users have to zoom to a higher resolution in an adjacent region and then pan over to the desired region. Enabling pan at low resolutions would allow users to drag the image so that these regions are available for direct zooming.

**Comment by manthey** [comment]
There is an optional clamp for panning.  We could turn it off -- though it means that you can pan arbitrarily to an area where the image doesn't exist.  Another way would be to allow panning up to, say, half the image size off the screen.  At high magnifications you could still zoom and pan to a nowhere location, but for low magnifications you would at least always see some of the image.

**Comment by cooperlab** [comment]
Confirmed this works. Let's go with 10%.
