### ISSUE TITLE
Polygon tool - click+trace annotation mode

### ISSUE THREAD

**Issue by cooperlab** [DigitalSlideArchive/HistomicsTK#598]
Make it possible to have line-line tracing with the polygon tool.

@kheffah

**Comment by kheffah** [comment]
For context, this would also solve issues #505 and #481 (beside the aesthetic value of course).

**Comment by manthey** [comment]
As soon as https://github.com/OpenGeoscience/geojs/pull/976 is merged, we can update the version of geojs that we use and free-hand polygons will be enabled.

**Comment by kheffah** [comment]
Wonderful! Thank you!

**Comment by manthey** [comment]
Resolved by https://github.com/OpenGeoscience/geojs/pull/976 and #601.
