### ISSUE TITLE
TileSourceException: No available tilesource

### ISSUE THREAD

**Issue by obruck** [DigitalSlideArchive/HistomicsTK#607]
I am using Python 3.7.1. and have problems importing images. All necessary modules should be installed but I get the error below. Would you know what is the reason for the error?

```
>>> ts = large_image.getTileSource("Desktop/test/TCGA-UW-A7GI-01Z-00-DX1.4A1709FC-F8F3-4509-A011-10CBF1B53DA9.svs")
TileSourceException: No available tilesource for Desktop/test/TCGA-UW-A7GI-01Z-00-DX1.4A1709FC-F8F3-4509-A011-10CBF1B53DA9.svs
---------------------------------------------------------------------------
TileSourceException                       Traceback (most recent call last)
<ipython-input-259-a00b7c266699> in <module>
----> 1 ts = large_image.getTileSource("Desktop/test/TCGA-UW-A7GI-01Z-00-DX1.4A1709FC-F8F3-4509-A011-10CBF1B53DA9.svs")
/anaconda3/lib/python3.7/site-packages/large_image/tilesource/__init__.py in getTileSource(*args, **kwargs)
     76     if not len(AvailableTileSources):
     77         loadTileSources()
---> 78     return getTileSourceFromDict(AvailableTileSources, *args, **kwargs)
     79 
     80 
/anaconda3/lib/python3.7/site-packages/large_image/tilesource/__init__.py in getTileSourceFromDict(availableSources, pathOrUri, *args, **kwargs)
     64         if availableSources[sourceName].canRead(sourceObj):
     65             return availableSources[sourceName](sourceObj, *args, **kwargs)
---> 66     raise TileSourceException('No available tilesource for %s' % pathOrUri)
     67 
     68 
TileSourceException: No available tilesource for Desktop/test/TCGA-UW-A7GI-01Z-00-DX1.4A1709FC-F8F3-4509-A011-10CBF1B53DA9.svs
```

**Comment by manthey** [comment]
Do you have libopenslide installed?  SVS files use the svs tile source, which uses the `openslide-python` module and libopenslide.  If you do `python -c 'import openslide'`, does it work?

**Comment by obruck** [comment]
Thanks for the fast answer. The command `python -c 'import openslide'` works.

**Comment by manthey** [comment]
To be certain, the path you are specifying works from your current environment?  That is `os.path.getsize("Desktop/test/TCGA-UW-A7GI-01Z-00-DX1.4A1709FC-F8F3-4509-A011-10CBF1B53DA9.svs")` returns something sane (on my local copy of that TCGA file, the size is 1,463,222,614 bytes, so I'd expect you to have the same).

**Comment by obruck** [comment]
Dear @manthey , I don't know what eventually was the issue, but I managed to get this to work. Anyone facing similar error messages, the solution for me was to reinstall Python. I also changed my IDE from Rodeo to Spyder. My guess is that all openslide dependencies were not somehow connected for an unknown reason, and this has nothing to do with Histomics itself. Thanks for the help. The issue can be closed.

**Comment by pbushel** [comment]
My code threw the same error when using large_image v1.1.0.  

ts = large_image.getTileSource("652123.svs")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/large_image/tilesource/__init__.py", line 79, in getTileSource
    return getTileSourceFromDict(AvailableTileSources, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/large_image/tilesource/__init__.py", line 67, in getTileSourceFromDict
    raise TileSourceException('No available tilesource for %s' % pathOrUri)
large_image.exceptions.TileSourceException: No available tilesource for 652123.svs

I had it uninstalled and then installed version 1.0.4 and all was fine.

**Comment by bryanwong17** [comment]
Hi @pbushel , I tried installing version 1.0.4, but it still did not work. Could you please let me know how to make it work? Should I put an additional file?
