### ISSUE TITLE
ValueError: Does not understand character buffer dtype format string ('?')

### ISSUE THREAD

**Issue by zzzghm** [DigitalSlideArchive/HistomicsTK#616]
When I am trying the nuclei segmentation on Windows 10, basically same code as your demo https://digitalslidearchive.github.io/HistomicsTK/examples/nuclei-segmentation.html
I got the ValueError
ValueError                                Traceback (most recent call last)
<ipython-input-21-0160eb114e4d> in <module>
     22 
     23 im_nuclei_seg_mask, seeds, maxima = htk.segmentation.nuclear.max_clustering(
---> 24     im_log_max, im_fgnd_mask, local_max_search_radius)
     25 
     26 # filter out small objects

c:\users\surface\histomicstk\histomicstk\segmentation\nuclear\max_clustering.py in max_clustering(im_response, im_fgnd_mask, r)
     53     # find local maxima of all foreground pixels
     54     mval, mind = _max_clustering_cython(
---> 55         im_response, im_fgnd_mask, r
     56     )
     57 

_max_clustering_cython.pyx in HistomicsTK.histomicstk.segmentation.nuclear._max_clustering_cython._max_clustering_cython()

ValueError: Does not understand character buffer dtype format string ('?')

No matter how I change the type of im_fgnd_mask in max_clustering_cyphton.pyx, max_clustering.py or the called function, the error still there.
Do you have any idea how to fix it?

**Comment by zzzghm** [comment]
![image](https://user-images.githubusercontent.com/25622904/54307556-f5f07480-4599-11e9-88cb-29cc0d6f963f.png)

**Comment by dgutman** [comment]
Any chance you can try this in a virtual box or similar?  We haven't donr
much if any windows testing since none of our Dev team owns a windows
machine...


😃

**Comment by cooperlab** [comment]
You need to provide some additional code or data for the inputs to get feedback. This is very likely related to how you are generating the inputs and is not a Windows specific problem.

**Comment by zzzghm** [comment]
I just used the exact same codes as your demo: 
https://digitalslidearchive.github.io/HistomicsTK/examples/nuclei-segmentation.html

**Comment by YiyuHong** [comment]
@zzzghm Have you solved the problem, I have the same problem. It seems like cython use different datatype on linux and windows

**Comment by kvijaysai** [comment]
I am also using Window system and followed the example code from https://digitalslidearchive.github.io/HistomicsTK/examples/nuclei-segmentation.html
Although I change the datatypes, I am getting a similar error

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-83-1807f71b9291> in <module>
      2 local_max_search_radius = 10
      3 imNucleiSegMask1, Seeds, Max = htk.segmentation.nuclear.max_clustering(
----> 4     imLog, imFgndMask, local_max_search_radius)
      5 
      6 # compute nuclei properties

c:\iu\spring 2020\csci-b 657 computer vision\project\histomics\histomicstk\histomicstk\segmentation\nuclear\max_clustering.py in max_clustering(im_response, im_fgnd_mask, r)
     53     # find local maxima of all foreground pixels
     54     mval, mind = _max_clustering_cython(
---> 55         im_response, im_fgnd_mask.astype(np.int32), r
     56     )
     57 

_max_clustering_cython.pyx in histomicstk.segmentation.nuclear._max_clustering_cython._max_clustering_cython()

ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
```

**Comment by manthey** [comment]
I think this is some sort of compatibility issue with the version of numpy and Cython on your Windows machine.  Specifically, what versions of Python, numpy, and Cython do you have installed?  Are there other versions of Python in the path?  Are there any environment variables set for PYTHONPATH, Cython, or numpy?

None of our developers are using Windows, so this is tricky for us to help.

**Comment by cooperlab** [comment]
I took a look at this today and I think the problem is that some numpy types are platform specific and so this is mismatching with what Cython expects on Windows. I don't get a long long from uint32 for example on my Mac.

**Comment by kvijaysai** [comment]
On my windows machine, I have:
numpy 1.18.1
Cython 0.29.15
python 3.7.6
and specifically, this python is from Anaconda3

There are no other versions in my system or in the path. And there are no environment variables set for PYTHONPATH, Cython, or numpy

I still get the same error.
Thanks for the quick responses, hoping it to get it resolved soon.

**Comment by xhm1014** [comment]
I encountered the same error on win10 system. Have not found good solutions.

**Comment by AbdulRahimShihabuddin** [comment]
I'm facing the same issue @kvijaysai . Have you found the solution?

**Comment by AbdulRahimShihabuddin** [comment]
@cooperlab Have you solved this problem? I'm working on Windows 10 and I'm getting the same value error :Buffer dtype mismatch, expected 'long' but got 'long long'

**Comment by cooperlab** [comment]
@AbdulRahimShihabuddin I have not worked on this since I don't have a Windows machine.

The problem is in the platform defined types https://numpy.org/doc/stable/user/basics.types.html. If someone who is a Windows user could take a look at this that would be great.

**Comment by ashutosh16399** [comment]
@AbdulRahimShihabuddin @xhm1014 @kvijaysai @cooperlab  anyone solved this? I'm facing the same issue "Buffer dtype mismatch, expected 'long' but got 'long long'".

**Comment by manthey** [comment]
This is a cython/numpy datatype issue that is specifically on line https://github.com/DigitalSlideArchive/HistomicsTK/blob/master/histomicstk/segmentation/nuclear/_max_clustering_cython.pyx#L10.  C compilers specify that `int` is at least as big as a `short` and no larger than a `long`.  We are passing `np.int32` and specifying `int` -- in our test environments this works, but `int32` is not necessarily the same as `int.  In the problem environments, it looks like `int` maps to `long long` (this surprises me as it is outside the C-spec unless `long long` is the same as `long`).  Maybe changing that line to explicitly accept `long` rather than `int` would make things work in both our usual test linux environment and in the problem environments.

It wouldn't surprise me if we also need to change data types on https://github.com/DigitalSlideArchive/HistomicsTK/blob/master/histomicstk/segmentation/nuclear/_max_clustering_cython.pyx#L25-L26, too.
