### ISSUE TITLE
Interruption of annotation causes major lag

### ISSUE THREAD

**Issue by kheffah** [DigitalSlideArchive/HistomicsTK#617]
When I am doing some annotations and I leave the browser to another tab to do some other work or to look up something, when I go back to continue annotation the interface shows major lag and degradation in performance. Often I am forced to reload the page to get it to work smoothly again. I remember this was discussed in an earlier issue and we assumed it was fixed (can't find it though). 
Thanks!

**Comment by kheffah** [comment]
**Note:** This may be a low RAM issue. We'll see if this persists once we restart the server. However. this issue was there before but it was mild, so I still recommend checking it out even if it gets mitigated when the RAM issue is fixed.

**Comment by manthey** [comment]
I think this was fixed in PR #605.  Are you using a version that includes that?  Prior to that change, switching tabs and switching back would reload annotations (in case they were edited in a different tab).  Now it doesn't unless they have actually changed.

**Comment by kheffah** [comment]
Fixed by PR #605 . @manthey You're right, we were using a version before this PR. Thanks!
