### ISSUE TITLE
Annotation style change - incomplete list

### ISSUE THREAD

**Issue by cooperlab** [DigitalSlideArchive/HistomicsTK#619]
When making creating new annotations in a session, the styles listed in the right-click menu are not complete (lists only "default"). The list updated when I returned to the slide later to continue annotating.

Also, when the list of styles is long, objects cannot be moved to some of the less frequently used styles since they do not appear on the list. If possible, make the list scrollable in some way.

**Comment by kheffah** [comment]
Related to what was discussed in todays's meeting: Current context menu is truncated to 10 style elements, ordered by number of uses. When there is a very large number of heavily used styles, this makes it impossible to get a new style into the context menu that is not yet heavily used in the slide. Suggested fix: Show all styles, ordered by recency of use as opposed to number of uses, and make the context menu scrollable.

**Comment by manthey** [comment]
I believe this was fixed in #646 and #648.

**Comment by kheffah** [comment]
@manthey Yes it was, thank you so much!
