### ISSUE TITLE
Lasso multiselect

### ISSUE THREAD

**Issue by kheffah** [DigitalSlideArchive/HistomicsTK#620]
Having the current multi-select feature has been very useful; others and I have been using it extensively for correcting annotations. The current multiselect needs one click per object, which is great for objects that are far apart. However, there are situations (appearing more and more frequently recently) when there are many annotations close to each other that need deletion; I'm talking 30+ objects. A lasso multiselect would be much more appropriate for bulk selection and editing. I'm not suggesting that we replace the current multiselect, but that we add an additional "annotation tool" beside the {point, rectangle, polygon, line, LASSO} which, when selected, allows the user to draw a polygon and select everything enclosed within it.

**Comment by manthey** [comment]
Not quite the same, but relatively easy to implement, would be to allow selecting a rectangular area (for instance, via ctrl-shift-drag).  This already generates an internal event for any annotation completely within the rectangle.  We could attach this event to the select.

Alternately, after drawing a polygon (or even while drawing), we can call the internal feature polygonSearch functions to determine which annotation elements are completely or partially inside the drawn polygon.

**Comment by kheffah** [comment]
@manthey Thank you! Either sounds OK to me. I think any functionality that allows for one-click+drag bulk selection of elements is sufficient. This would be soooooo helpful when implemented since many of the annotation cleanup efforts involve deletion or editing numerous "clustered" annotation elements.
