### ISSUE TITLE
Download/upload styles

### ISSUE THREAD

**Issue by cooperlab** [DigitalSlideArchive/HistomicsTK#621]
Add ability to upload and download styles (these are stored locally in the browser).

Having users in annotation studies create their own styles leads to harmonization problems, and also requires more training. Having the ability to download / upload styles would allow the study coordinator to create the style collection and to distribute this to participants.

This is a high priority.

**Comment by manthey** [comment]
This sort of exists as a setting in the HistomicsTK plugin settings.  You can set the default styles, and then a user can reset their styles to those defaults (or it starts with those defaults if they haven't ever set them).

**Comment by kheffah** [comment]
@manthey You mean this? I'm not sure how to use it. Can this somehow be used/adapted to directly load an annotation style that someone else created, or to download a specific annotation style?

![image](https://user-images.githubusercontent.com/22067552/54714608-b8ef2980-4b27-11e9-910f-22e10a9560bb.png)

**Comment by manthey** [comment]
If an admin clicks "save as defaults", a json representation of the styles is stored in the plugin settings.

In the HistomicsTK plugin settings, the defaults can be copied or set.  So you could click the save button you've shown on one instance, go to the plugin settings and copy the json string for styles, and then paste that json string on a different instance (or manually combine it with another json style specification string).

I'm sure this won't be convenient if you have to do it more than a few times, so we can certainly add export/import buttons to the style dialog if desired.

**Comment by kheffah** [comment]
@manthey Thank you for explaining; I'm not sure I fully understand. How can I access the plugin settings, through the API? Or do I have to have access to the server where DSA is installed? We have ~20 styles, and each project has its own set of styles. I think what I envision, and @cooperlab  can chime in here if there's a better way, is that I share, say, 20 JSON style files with all the users and just tell then to drag and drop them so they would be loaded onto their browser.

**Comment by manthey** [comment]
If you have admin rights, you can go to Admin Console -> Plugins and click on the gear icon next to HistomicsTK.  You'll see something like this:
![image](https://user-images.githubusercontent.com/8781639/54715469-ed63e500-4b29-11e9-8393-393232a50bc0.png)

A drag-and-drop facility would be much better...

**Comment by kheffah** [comment]
Ah!!! If only I knew this existed earlier :) Thank you! Like you said, drag and drop is still probably a more optimum way to do this, especially when there are multiple projects happening and we don't want users from different projects seeing each other's labels.

**Comment by cooperlab** [comment]
Each project will have its own set of styles. So upload/download would be best (doesn't have to be drag and drop - button will suffice).

This will allow the coordinator can generate the styles for their project, download them, and distribute the styles for each user to upload.

It will also allow people to clear their cache without redoing all styles manually.

**Comment by kheffah** [comment]
**Suggested implementation based on today's meeting:** 
Styles are "grouped" together in a a single file, something like an xml or JSON, which we'll call a "config" file. When you open an item (slide), the system looks for a style config file in the same folder as the slide. If not, it looks for the folder's parent, until it finds a config file to use (all the way up to the collection. If not, default style options are displayed.

**Comment by cooperlab** [comment]
I had some more discussions with @kheffah about this today. This will make a big difference in the quality of annotation data we collect and the ease of running these annotation projects.

Uploading a style file to a folder, subfolder, or slide within the DSA interface is a good idea. Should be no problem for project coordinators or more experienced users who are able to generate their own styles.

Where to download is less clear. Someone creates a set of styles, presumably in the HistomicsTK interface, and then wants to apply these to a collection, folder, or project. Where do these styles go by default when the are created, and where can they be download?

Also need to deal with the issue of behavior when our users play around and add styles when a style file already exists. I don't think we should prevent this, and these styles should appear in their menu but not be added to the config. Perhaps we shouldn't allow them to delete styles that exist in the style file though. @kheffah thoughts?

**Comment by kheffah** [comment]
@cooperlab Thanks for the mention. I think one way we can make this work is to have the config file follow the same permission model as the items (slides). So if I am an admin and I want to avoid having people creat their own styles, I can simply set the permission of the config file to admin-only. If not, then I can given the user permission to the config file, and hence any style they create would also edit the config file. Having the "look for closest folder with a config file" model makes this really flexible, since the admin can place a config file proximal to the slide with broad access permission if they want the user to be able to edit it, but to keep the most "distal" (close to root folder) config file as an admin-only access.

**Comment by cooperlab** [comment]
Let's hear from David M. what's easiest from an implementation perspective. This is a minor issue, and I think the most important thing is being able to lock down these styles and not have to re-add them when a volunteer mistakenly deletes one.

**Comment by manthey** [comment]
I've got a working, but not quite complete implementation of this.  The styles dialog gets two new buttons:
![image](https://user-images.githubusercontent.com/8781639/55083332-c05b8900-5079-11e9-9cc0-230178b4b6ad.png)

Export will immediately offer to download the current set of styles, including unsaved changes that have been applied in this dialog.

Import has a check box.  If not checked, importing a file will merge with the existing styles.  Styles with the same name will be modified.  Styles that don't exist are added.  If the check box is checked, all styles are replaced with the new file.

I'm soliciting feedback on the UI -- For the import merge vs replace, I thought the checkbox was simple (it has a tooltip that reads 'Completely replace all styles if checked; add to and modify existsing styles if unchecked'), but it may not be very clear, or perhaps we should pick whether we just always do merge or replace.

**Comment by kheffah** [comment]
@manthey Love this implementation! I think keeping the checkbox is helpful. I have a recommendation on the mechanism of merging, however. If a style already exists, I recommend completely replacing it with the uploaded style, not creating a hybrid of the two. Otherwise, I think this is perfect!

**Comment by cooperlab** [comment]
That is slick @manthey. Look perfect to me.

**Comment by cooperlab** [comment]
Should I postpone creating the UI training video? What is the eta on getting this feature integrated?

**Comment by kheffah** [comment]
One question: does it relay on "config" files as we discussed? Or did you find a better/simpler/different way to implement this?

**Comment by manthey** [comment]
@kheffah Okay -- merge will replace existing styles with the same name rather then creating a hybrid.

**Comment by manthey** [comment]
This doesn't do anything with config files -- That will be a different PR later.  The exports from this would be usable as those config files, though.

**Comment by manthey** [comment]
@cooperlab I need to add some validation checks (make sure when you pass bad input it does something sensible) and write a few tests.  I hope to have a PR today or tomorrow (and then @jbeezley or someone else will need to review it before it gets merged).

**Comment by kheffah** [comment]
@manthey Got it. Thank you!
