### ISSUE TITLE
Resetting rotation to zero 

### ISSUE THREAD

**Issue by kheffah** [DigitalSlideArchive/HistomicsTK#635]
Quite often with the multiselect tool, users accidentally rotate the slide. This happens because while holding down the control key, sometimes instead of clicking, the users click and drag the mouse a little bit. This (Ctrl+Click and drag) causes slide rotation. Currently there's no way to reset the rotation to zero. Even reloading doesn't work, since the URL shows "%bounds=-........." so the reloaded slide is also rotated. This had caused problems, since the bounding boxes (rectangles) created thereafter are ever-so-slightly rotated (sometimes without the user's knowledge) relative to the item and hence their coordinates are not consistent (some rotated, some not). 
I suggest:
1- A simple "reset- rotation" button or keyboard shortcut.
2- +/- A checkbox to disable rotation that is unchecked by default and needs to unchecked if needed.

**Comment by manthey** [comment]
There is already a keyboard shortcut: `0`

**Comment by kheffah** [comment]
Wonderful! :)

**Comment by manthey** [comment]
We actually get the default geojs keyboard shortcuts unless we specify otherwise, so other number keys will jump to specific zoom levels, `<` and `>` will rotate, and arrow keys nudge the image.  `shift` and `ctrl` affect how big the rotation and arrow key movement is.

**Comment by kheffah** [comment]
@manthey This is great to know. Any other shortcuts we have? Perhaps there is a list somewhere?

**Comment by manthey** [comment]
It isn't listed anywhere sensible, just in the code here: https://github.com/OpenGeoscience/geojs/blob/master/src/mapInteractor.js#L262-L277

We should probably have a short help page accessible via ? icon which would show a dialog with keyboard shortcuts and some other brief explanations.

**Comment by kheffah** [comment]
Nice! I definitely agree, having it somewhere readable for the end user would be helpful.
