### ISSUE TITLE
Name change -> DSA

### ISSUE THREAD

**Issue by cooperlab** [DigitalSlideArchive/HistomicsTK#644]
HistomicsTK has been used throughout the UI, code, and filenames for DSA functionality. Should be changed to DSA.

**Comment by manthey** [comment]
This should include renaming the docker histomicstk_main to dsa_main (or something similar).

**Comment by manthey** [comment]
Relevant code has been moved to https://github.com/DigitalSlideArchive/digital_slide_archive and https://github.com/DigitalSlideArchive/HistomicsUI.  Names have been changed in those repos.  We still need to remove the UI and deployment code from this repo.

**Comment by manthey** [comment]
Finished with #833.
