### ISSUE TITLE
Initial feature set - implementation

### ISSUE THREAD

**Issue by cooperlab** [DigitalSlideArchive/HistomicsTK#66]

**Comment by cdeepakroy** [comment]
@cooperlab can we assign this to @slee172 while you work on nuclei segmentation?

**Comment by cdeepakroy** [comment]
Seems like we have to port [FeatureExtraction.m](https://github.com/cooperlab/ActiveLearning/blob/master/segmentation_pipeline/FeatureExtraction.m) in the ActiveLearning repo. Scikit-image has support for [regionprops](http://scikit-image.org/docs/stable/api/skimage.measure.html#regionprops), [Haralick features based on the gray-level cooccurence matrix (GLCM)](http://scikit-image.org/docs/stable/api/skimage.feature.html#greycoprops), and a few other [features](http://scikit-image.org/docs/stable/api/skimage.feature.html). We can use the [pandas.DataFrame](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html) to store the features.

**Comment by cdeepakroy** [comment]
It would be nice to implement the ExtractFeatures function in such a way that i can tell which features to compute rather than computing all of them. Then, in the front-end website we can have way to select features/feature-groups via check boxes.

**Comment by cooperlab** [comment]
Great idea - assign away.

@slee172 capture the easy features first. Let's just dump all feature definitions into a single function for now. Long term we need to group these so that users can select subsets for computation.

**Comment by cooperlab** [comment]
@cdeepakroy definitely. We need to find the right granularity so that we don't overwhelm the users. Shape is an obvious sub-category. Beyond that things get harder to categorize nicely.

**Comment by cdeepakroy** [comment]
We can use the same strategy as the [graycoprops](http://scikit-image.org/docs/stable/api/skimage.feature.html#greycoprops) in scikit-image to allow the user of the feature-extraction function to explicitly specify the features/feature-groups he wants to compute.

**Comment by cdeepakroy** [comment]
For the GUI, below is what ilastik seems to be doing:

![image](https://cloud.githubusercontent.com/assets/1923534/14501493/c0aeff42-0174-11e6-95c3-fb36e9f5a9c8.png)

**Comment by slee172** [comment]
@cdeepakroy looks good to me

**Comment by cooperlab** [comment]
I looked at this - I think we can go with similar groupings for 'shape', 'intensity', 'edge', 'texture', and a category for 'special' to accommodate things that don't map nicely to the other four groups. 

May be better to allow users to define parameter ranges in textboxes, or a comma separated list of discrete values etc.

**Comment by slee172** [comment]
@cdeepakroy As you said, Scikit-image supports for regionprops as follows:
https://github.com/scikit-image/scikit-image/blob/master/skimage/measure/_regionprops.py#L348

I just tested it as below:
############################################
from skimage import data
from skimage.feature import canny
from skimage.measure import regionprops
from skimage.measure import label

# read sample
Image = data.coins()

# detect edges of sample using canny filter
edges = canny(Image, sigma=3,
                     low_threshold=10,
                     high_threshold=80)

# label edges
label_image = label(edges)

# extract feature information
props = regionprops(label_image)
print(props[0].centroid)
############################################

@cooperlab I think the next step is to read tile images from a svs file and extract featrues from them. What do you think about using ReinhardSample.py to get tile images?  

For pandas, this would be a good way of dealing with those features. Because pandas provides HDFStore using read_hdf, we could handle the features once we store them on HDF5. But, at this time, how about handle the features directly without HDF5? I think some issues shoud be solved before using HDF5.

**Comment by cooperlab** [comment]
@slee172 - for now just assume that someone is providing a label image. You are working backwards from the feature extraction, I am working forwards from the segmentation, and we will meet in the middle.

Please test performance for reading/writing large HDF5s. I have heard complaints that this is slow in Python. Each slide will contain up to ~1M objects with 40-200+ features each. Data should be organized in the HDF5 so that we can access the features from individual tiles without reading the entire file into memory.

**Comment by cooperlab** [comment]
@cdeepakroy I would be skeptical about stashing feature data in a database but am open to hearing about this. Will probably be very slow and results may be discarded frequently. Will be easy to test though with some random matrices.

**Comment by cooperlab** [comment]
@cdeepakroy Also keep in mind that in the future we may be doing regional analysis including classification. Here features are defined over a dense grid on this image instead of sparsely over objects in the slide. Not trying to get ahead of ourselves, but I don't see those types of features being very compatible with a DB since they are essentially images themselves.

**Comment by zachmullen** [comment]
@cdeepakroy I share @cooperlab 's concern, depending on the size of the dataframe; MongoDB (sensibly) limits documents to <=16MB in size, so anything that doesn't fit in that should be stored as a file.

The real question is what information we want to *index* on. Whatever that ends up being, that's what we should put into the database so we can filter by it.

**Comment by cooperlab** [comment]
@zachmullen We clearly want to index on location. We may want to index on the values of the features themselves though too in some cases. @dgutman Any thoughts on this?

**Comment by zachmullen** [comment]
Location should be quite straightforward, hopefully other features will be as well. Dense/raster data should be stored as files, and the documents in the database should just contain file ID's.

**Comment by cooperlab** [comment]
OK. I thought of HDF5 originally as kind of a compromise - it's a file but you can organize it for fast spatial access. That wouldn't support fast feature "indexing" though.

**Comment by zachmullen** [comment]
HDF5 is a good candidate as the data format to store the file, and we could write special plugin code to get data out of it if we need to expose spatial indexing, and then we can use the database to add any external indexes that we needed. Of course, at that point we'd want to make sure that the file data was immutable, lest we run into data synchronization issues.

**Comment by zachmullen** [comment]
(netcdf has python bindings, so using it within a girder plugin would be straightforward)

**Comment by cooperlab** [comment]
It will be immutable. Most datasets will fall into two categories - those that we host for an analysis or external resource (permanent) or those that are generated for development/tuning of algorithms (temporary). Neither would be modified, but insertion/generation needs to be fast for the second case.

**Comment by slee172** [comment]
@cdeepakroy A function for basic feature extraction is implemented. The function reads a label image, grayscale image (as an example), and some parameters, and returns a panda data frame.

**Comment by cooperlab** [comment]
@slee172 I did some work on the boundary cleanup and other misc. things we will need to finish the nuclear segmentation pipeline. My goal is to do a PR by Weds that should capture the segmentation and utility functions.

**Comment by slee172** [comment]
@cooperlab  sounds good. Before then, I will add other features to the panda data frame.

**Comment by slee172** [comment]
@cooperlab Generating a group of FSDs features from labels requires some functions such as "GetBounds", "PixIndex", "InterpolateArcLength", and so on. I'm currently using those functions in one python file at this time. Do you have any idea of how to upload those functions into here? I think one of straightforward idea is to push them separately in different file.

**Comment by cooperlab** [comment]
Only add them as individual files if they will be utilized by other HistomicsTK functions (doubtful). Otherwise add them as helper functions inside of another file.


Lee Cooper, Ph.D.
Assistant Professor of Biomedical Informatics
Assistant Professor of Biomedical Engineering
Emory University School of Medicine - Georgia Institute of Technology
lee.cooper@emory.edu
tel: (404) 712-0110
________________________________

**Comment by slee172** [comment]
Adding them as helper functions could be better.

**Comment by cooperlab** [comment]
I think we have a mature initial feature set now and can close this issue.
