### ISSUE TITLE
Navigating virtual folders -- forward and backward arrows

### ISSUE THREAD

**Issue by kheffah** [DigitalSlideArchive/HistomicsTK#660]
When using virtual folders to organize data, the notion of "next" and "previous" slide break down. Instead, the DSA system takes you to the original folder where the slide is located, so the forward/backward arrow (next/previous item) take you to slides before/after the current slide in the **original**, not virtual, folder.
Suggested handling:
When the slide is visited from a virtual folder, the arrows should move within the virtual folder as opposed to the original folder where slide is stored.

**Comment by manthey** [comment]
Currently, we only track what item we are viewing -- we'll have to also track how we got to it, since with virtual folders the item conceptually exists in multiple places.

**Comment by kheffah** [comment]
@manthey Yes please, that would be great! It's also more logical, since like you said virtual folders make it possible to arrive at the same item from multiple places. I know it's hard to guess, but would this be a feasible fix? I have 1000+ slides in a virtual folder that I will have a pathologist navigate and I would hate to have them scroll down to their item of choice and look for it every time .. especially since only spend a minute or so per item to confirm some pre-existing annotations.

**Comment by manthey** [comment]
It is certainly feasible, but I'll have to look a bit more to know the magnitude of work.  At the very least, the next_image and previous_image endpoints will need a context (the conceptual parent folder) passed to them, and we'll need to add that parent to the navigation route.

If you open an image via "Open image", we have the context.  If you open it via "Annotated images", then it isn't clear what the context should be -- I would initially use the actual parent folder by default, but if you are already viewing another image and both it and the selected image share a conceptual parent, then I would maintain the conceptual parent as the context.

**Comment by kheffah** [comment]
I rarely use 'Annotated images", but as you pointed out, the most intuitive way to handle that would be to use the "real" parent folder by default when using the 'Annotated Images' path to open the image.
