### ISSUE TITLE
resource/{id}/items does not support virtual folders

### ISSUE THREAD

**Issue by dgutman** [DigitalSlideArchive/HistomicsTK#665]
Would be very useful to add a flag to enableVirtualFolderSupport: True/False or similar to allow it to properly deal with this use case.  

![image](https://user-images.githubusercontent.com/713166/58914690-2d7c4200-86ed-11e9-9a1a-2d81d86adc20.png)

GET /resource/{id}/items
Get all of the items that are children of a resource.

**Comment by manthey** [comment]
This is added in https://github.com/DigitalSlideArchive/digital_slide_archive/pull/37.
