### ISSUE TITLE
Support poll option for 'girder-install web --watch'

### ISSUE THREAD

**Issue by tymiao1220** [DigitalSlideArchive/HistomicsTK#668]
Hi, I am try to use vagrant for extra plugin development based on HistomicsTK, I am wondering
how should I use `girder-install web –watch-plguin` to monitor file changes outside VM?

What I did now is vagrant up which sync folder to `/vagrant/` and then I symlink sync folder `/vagrant/plugins` to `/opt/HistomicsTK/girder/plugins` which I think should work but it is not.

And it seems work when I develop new plugin in girder, but get no luck on HistomicsTK, should I make some change on VagrantFile?

Thanks.

**Comment by manthey** [comment]
This should work properly with the Girder 3 deployment (see https://github.com/DigitalSlideArchive/digital_slide_archive).
