### ISSUE TITLE
Combine with OpenSeadragon on JavaScript

### ISSUE THREAD

**Issue by zzzghm** [DigitalSlideArchive/HistomicsTK#671]
I had an web-viewer based on OpenSeadragon, and I would like to combine the viewer with HistomicsTK and girder to better analysis and manage the whole slide images. I am wondering where can I find lower level code that you called the OpenSeadragon as a function that I can modify, in that case, I can start from there to combine our viewer with HistomicsTK. Thank you!

**Comment by manthey** [comment]
Since you made an issue in large_image (https://github.com/girder/large_image/issues/360), I'll close this one in favor of that one.
