### ISSUE TITLE
problem while importing grammar-check package in python

### ISSUE THREAD

**Issue by alagappan7** [DigitalSlideArchive/HistomicsTK#673]
C:\Users\Vishal>pip install --user --upgrade grammar-check
Collecting grammar-check
  ERROR: Could not find a version that satisfies the requirement grammar-check (from versions: none)
ERROR: No matching distribution found for grammar-check

This is the error i get while importing the package. All prerequisites are satisfied.

**Comment by manthey** [comment]
This seems to be a known bug in grammar-check: https://github.com/viraja1/grammar-check/issues/7

This doesn't seem to have anything to do directly with HistomicsTK, so closing this issue.
