### ISSUE TITLE
Sampling annotations at low power -- ideal?

### ISSUE THREAD

**Issue by kheffah** [DigitalSlideArchive/HistomicsTK#676]
When displaying annotations at low power, they are sampled to prevent cluttering the field. This is alright when thinking about point annotations, but starts to make less sense when considering polygonal annotations. In one project where I use HIstomicsTK to inspect segmentation results on a whole-slide level, "pockets" of absent boundaries appear at low power, like so:

![image](https://user-images.githubusercontent.com/22067552/62825358-4d5e3500-bb78-11e9-97ee-feff5491da07.png)

Then when I zoom in, I realize they were just not chosen for display:

![image](https://user-images.githubusercontent.com/22067552/62825366-64048c00-bb78-11e9-97d9-a60ca775f1bb.png)

This makes is quite difficult to review results on low power to look for places with misclassification, as the viewer is not certain whether this is due to annotation sampling or misclassification. My suggestion is to use static overlays at low power (i.e. images of the annotation field) which gets just resize at different magnification levels, until a critical threshold (potentially controlled by the user) when the actual polygons are rendered and not a static image. I realize this is a complex process, but it will solve some of the key performance issues that slow down the rendering considerably as the number of annotation polygons goes up to the tens of thousands. Currently, the only way I can review results without lag in performance is to post the annotation polygons into multiple documents and to view them one by one. With an overlay (see issue #577 ), that would not be needed, and I can just view everything at low power and only interact dynamically with the elements when I zoom to an area of interest. 

There's definitely pros and cons to both the existing and suggested method.

**Comment by cooperlab** [comment]
This has got us before when looking at nuclei detection algorithms and I don't think we have an elegant solution. I feel like we should be able to guarantee full rendering of annotations beyond a certain zoom level.

**Comment by kheffah** [comment]
@manthey Just to summarize what we discussed in today's meeting:

- **Heatmaps:** Bad idea because there are multiple styles (red, blue, green, etc), each would require its own heatmap which is too complex.

- **Static overlays:** Good idea but very time consuming and complex to implement. Potantially could make things very fast because the overlay would be rendered on the server side and served to the user in tiles just like the whole slide image itself. The problem is that the extra rendering on the server side would put load on the server and would require the server to use a headless browser compatible with the client. It will need a lot of infrastructure.

- **Showing centroids:** Most practical solution and potentially very scalable too, so this is the option we're going with for the time being.

**Comment by kheffah** [comment]
Closed by: https://github.com/girder/large_image/pull/371
