### ISSUE TITLE
Installing ITK with python as a package for ubuntu

### ISSUE THREAD

**Issue by zachmullen** [DigitalSlideArchive/HistomicsTK#68]
This is ITK v4.7 and I just verified on Monday that this works.

https://github.com/zachmullen/girder_training/blob/master/ansible/vagrant_playbook.yml#L17-L23

Then you can apt-get install `insighttoolkit4-python`

**Comment by cdeepakroy** [comment]
ITK is now available for docker CLIs via thanks to [this](https://github.com/DigitalSlideArchive/base_docker_image) base docker image.
