### ISSUE TITLE
Increase docker shared memory when running analyses modules

### ISSUE THREAD

**Issue by juliejsanchez** [DigitalSlideArchive/HistomicsTK#680]
Hi. Is there a way to increase the shared memory when running HistomicsTK docker images? I tried adding images but job being run seems slow compared to running the docker images independently and specifying the shared memory (docker run --shm-size). I hope you can guide me on this one or point me to some documentation I might have just missed. Thanks in advance :)

**Comment by manthey** [comment]
I think you'd have to modify girder-worker to alter how much memory is assigned to the docker images that run the analyses.  I don't think there is any convenient setting for doing so.  Perhaps when we refactor to Girder 3 we can expose a config file for girder-worker to modify how it runs docker containers.
