### ISSUE TITLE
Load images via large_image API

### ISSUE THREAD

**Issue by brianhelba** [DigitalSlideArchive/HistomicsTK#70]

**Comment by brianhelba** [comment]
Here's how we get access to the internal Girder API from a third-party Python app:
```
import sys
if '/path/to/girder' not in sys.path:
    sys.path.append('/path/to/girder')
from girder.utility import server as girder_server
girder_server.configureServer()
```
At that point, we could do something like:
```
from girder.utility.model_importer import ModelImporter

def loadImageFromGirderItem(girderItemId):
    item = ModelImporter.model('item').load(girderItemId, force=True)
    imageMetadata = ModelImporter.model('image_item', 'large_image').getMetadata(item)
    imageData = ModelImporter.model('image_item', 'large_image').getRegion(item, ...)
```

I realize now that the `ImageItem` class could probably use some more methods, particularly a convenience wrapper to graph the entire base image (though it will be huge), and a way to get the image data as a raw PIL image, rather than an encoded `bytes` object (though I also see a counter-argument to leaving this functionality at a lower level, in TileSource).

Feel free to consult with @manthey if I'm not around to discuss this more, but let's try to keep the discussion in this issue (and off email).

**Comment by cdeepakroy** [comment]
@brianhelba we should move this to the issue #47 or atleast i want to point you to that issue.

**Comment by brianhelba** [comment]
Oops. I'll close this, and copy my comment over to #47 .
