### ISSUE TITLE
Upgrade to GeoJS 0.9

### ISSUE THREAD

**Issue by brianhelba** [DigitalSlideArchive/HistomicsTK#72]
This contains zoom animations, which are an important feature.

**Comment by brianhelba** [comment]
@jbeezley Can you do this real quick? I'd GeoJS to be presenting its best face whenever possible.

We may want to consult with Charles to tweak some of the zoom animation speeds and elasticity. Practicing pathologists seem to love whatever SlideAtlas is doing.

**Comment by jbeezley** [comment]
HistomicsTK is using GeoJS from the large_image plugin, so this is already done.  I actually specifically disabled the discrete and animated zoom behavior to make it act like the old version, but that can be changed easily.  The relevant code is [here](https://github.com/DigitalSlideArchive/HistomicsTK/blob/master/web_client/js/views/visualization.js#L59-L76) with the `zoomAnimation` and `discreteZoom` keywords.

**Comment by jbeezley** [comment]
I believe this is no longer relevant.
