### ISSUE TITLE
Next and Previous buttons don't disable

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/HistomicsTK#744]
When you load an image that is in a folder with more than one image, the next and previous buttons are enabled.  If you then load an image that is by itself in a folder, they do not disable.  Further, when clicked, they cycle through the folder with multiple images.

**Comment by sgratzl** [comment]
isn't the cycling intentionally, at least in the code and test it does it:
```
            'next': allImages[(index + 1) % len(allImages)]
```

**Comment by manthey** [comment]
The problem is here: https://github.com/DigitalSlideArchive/HistomicsTK/blob/master/web_client/views/layout/HeaderImageView.js#L73-L75 (and similar for previous).  If there is only one image, `_nextImage` is not initially set and is not changed.
