### ISSUE TITLE
Update readthedocs

### ISSUE THREAD

**Issue by kheffah** [DigitalSlideArchive/HistomicsTK#749]
Once PR #734 is merged, we should update readthedocs to reflect the new documentation build. Currently it shows outdated documentation from 2016.

**Comment by kheffah** [comment]
@manthey shouldn't readthedocs be automatically updated? (this is probably a naive question :) ).

**Comment by manthey** [comment]
We stopped using readthedocs over two years ago in favor of deploying to Github pages (https://digitalslidearchive.github.io/HistomicsTK/), which should be automatically built and deployed whenever we merge to master.

Unfortunately, `travis-sphinx deploy` has been failing for a long time.  I just deployed manually, and PR #754 fixes the auto deployment.

**Comment by manthey** [comment]
Closing this as the gh-pages should once again update on merge to maste.
