### ISSUE TITLE
Install tool for anaconda

### ISSUE THREAD

**Issue by satotty** [DigitalSlideArchive/HistomicsTK#752]
Hi, I this module is great. I’d like to use this further for research but could you work on so that I could install histomicstk from anaconda?

**Comment by kheffah** [comment]
@satotty To complement @manthey's response. Here's how you can do so:

**1. Create conda environment.**

```python
conda create --name myenv
```

**2. Install pip inside your conda environment and activate it:**

```bash
conda install -n myenv pip
conda activate myenv
```
**4. Instal HistomicsTK using pip:**

```bash
pip install histomicstk
```

**Comment by sdasara95** [comment]
I tried creating the conda environment and pip installing histomicstk.
I am getting this error:
```
ERROR: Could not find a version that satisfies the requirement histomicstk (from versions: none)
```

Is it supported for a specific python version?
