### ISSUE TITLE
UI display of feedback from server

### ISSUE THREAD

**Issue by kheffah** [DigitalSlideArchive/HistomicsTK#757]
When there is heavy network traffic causing delays at the server side, or when the user is adding (or editing) elements in an annotation document with thousands of elements, the request being sent to the server may take a while to be sent. Currently, the only way to see if one's action (as an end user) has been officially received by the server is using the developer console to see the server response. It has happened on more than a handful of occasions where the user creates or edits many annotations and moves on to the next slide or closes the browser, not knowing that what he/she did did not actually get received by the server. 

**Proposed solution**: Some sort of message or loading bar to make the user aware that they should wait or if their request was not received by the server. This may be the same loading bar that may be used to address issue #592 .

**Comment by manthey** [comment]
@kheffah As of #761 we show a spinner on the Annotation panel.  If this is sufficient, please close the issue.

**Comment by kheffah** [comment]
Closed by PR #761
