### ISSUE TITLE
Remote MongoDB

### ISSUE THREAD

**Issue by Victordmdb** [DigitalSlideArchive/HistomicsTK#764]
Hi, I'm trying to attach histomicstk to a remote mongodb server (on mongodb atlas), but I'm having trouble figuring out if histomics allows it. 

In the `deploy_docker.py ` script there is a `--mongo` argument but it doesn't allow for assigning a custom IP. I tried modifying it to see if it could force `container_start_mongodb` to adopt an IP instead of one of the defaults but it doesn't seem to work after launching the docker instances.

Any recommendations?

**Comment by manthey** [comment]
If you are using the deploy_docker.py script, I think you have to specify --mongo=host to avoid starting a mongo docker container.  You also need to use a custom configuration for Girder (where you specify uri in the [database] section of the config).

**Comment by manthey** [comment]
Closing this.  Please reopen if there is still an issue.
