### ISSUE TITLE
Performing color normalization with local images instead of girder_client

### ISSUE THREAD

**Issue by asmagen** [DigitalSlideArchive/HistomicsTK#768]
I have my histopathology images stored locally and I would like to perform the color normalization as described in [this tutorial](https://digitalslidearchive.github.io/HistomicsTK/examples/color-normalization-and-augmentation.html) without using girder_client, or at the very least, using it as a local structure without uploading anything to a remote server. Is that possible?

Thank you

**Comment by manthey** [comment]
Yes.  All of the algorithms in the HistomicsTK toolkit work on files.  When run as a docker job by Girder Worker, it will get files from Girder.  If run any other way, the functions just take a file path.
