### ISSUE TITLE
Problem retrieving images used in tutorials for reproducing results

### ISSUE THREAD

**Issue by asmagen** [DigitalSlideArchive/HistomicsTK#769]
I was trying to reproduce the color normalization and tissue detection tutorials but the image retrieval via the girder client isn't working.

In the [former](https://digitalslidearchive.github.io/HistomicsTK/examples/color-normalization-and-augmentation.html) I get:
`girder_client.HttpError: HTTP error 400: GET http://candygram.neurology.emory.edu:8080/api/v1/item/5d817f5abd4404c6b1f744bb/tiles
Response text: {"message": "File cannot be opened via OpenSlide.", "type": "rest"}`

And in the [latter](https://digitalslidearchive.github.io/HistomicsTK/examples/tissue_detection.html) I get:
`Response text: {"identifier": "girder.utility.filesystem_assetstore_adapter.file-does-not-exist", "message": "File /opt/histomicstk/mounts/LOCAL_RAID/LocalRaidAssetStore/25/01/2501566dfb3327a8f097a89e363faaa1072618662e59b43eaabea8370bcde5ae26579355923ae494df35d650f9f093d5e07a5e8cd54f40727443ca2ae6837952 does not exist.", "type": "girder"}`

**Comment by dgutman** [comment]
So can you access the file in the main girder ui? This often happens when
you are trying to access a file.. that's not actually on the system.

**Comment by asmagen** [comment]
But this is the info and code that appears on the official documentation /tutorials. Isn't it supposed to work?

**Comment by dgutman** [comment]
So.. good point.  The code assumes you have the imaging data already...
Which in hindsight is ..   unreasonable.   Let me see if there are a set of
public images we can host to run these demos against.

**Comment by kheffah** [comment]
@asmagen there was an issue at the server last two weeks (RAID failure). The images are actually in a public folder so this should work. Can you try again and let me know if it's working?

**Comment by kheffah** [comment]
@asmagen Actually, never mind my last comment. @dgutman is correct about what's the issue. Technically, we should be hosting the test images on some public folder for people to be able to try out the "getter" requests (getting images/annotations from server) but not the "post" requests for visualizing results. We'll be doing that soon, but the code is applicable on any slide you have locally on your HistomicsTK instance. These are TCGA slides so are already public and available for download etc.

**Comment by kheffah** [comment]
@asmagen For now, so that you and other users can try out the data getters of the tutorials, I've modified the permissions of the API key used in the tutorial to be able to get (but not post) data. Can you try the tutorial again and tell me if it works for you?

**Comment by kheffah** [comment]
@asmagen Also, if you decide to try out hosting your own HistomicsTK instance and slides, you may want to take a look at this tutorial: https://www.youtube.com/watch?v=HTvLMyKYyGs
