### ISSUE TITLE
Refactor tests

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/HistomicsTK#820]
Refactor tests so they all run as part of CI.

Currently, there are tests associated with UI, deployment, algorithms, and girder client.  Some of the algorithm and girder client tests use unittest and are not currently run as part of CI.  This gives an artificially low value for reported code coverage.  Further, many of these attach to a remote server which is mutable and may cause the tests to fail in the future.

After removing UI and deployment from this repo, the remaining tests will no longer strictly require Girder.  They should be refactored so that they all run in CI.

I recommend:

- [x] Tests are refactored to use pytest.  This will result in some changes to how asserts are used.  For instance, in unittest we do `self.assertTupleEqual(a, b)` while in pytest we can do `assert a == b`.
- [x] Tests are refactored to run without a remove server.  Since we still want to test connecting to a Girder server, we can stand up a test server in a docker container, load it with appropriate data, and test against that.
- [x] Tests are configured to run using tox as the test harness rather than cmake.  This will make it easier to test multiple python versions.  To run new tests, rather than executing the test files directly, we would run something like `tox -e py37 -- -k algorithm_test`.

**Comment by manthey** [comment]
@kheffah Since you've been writing a lot of the recent tests, I want to make sure whatever changes we make are convenient to your work.

**Comment by kheffah** [comment]
@manthey Great! Thanks David. I'll refactor all the tests when we split the repo. That should be doable for sure.

**Comment by manthey** [comment]
I've been poking at a preliminary of this (see the remove-ui branch -- currently very much a work-in-progress).

**Comment by kheffah** [comment]
@manthey Nice!! Sorry if you already mentioned this, byt may I ask where the UI component will go? What repo will now host it?

**Comment by manthey** [comment]
UI has moved to https://github.com/DigitalSlideArchive/HistomicsUI.
Deployment has moved to https://github.com/DigitalSlideArchive/digital_slide_archive.

Before removing the UI code here, I'll make a 2.x-maintenance branch.  The main README will include links to the UI and deployment repos.

**Comment by kheffah** [comment]
Got it. That makes sense and will help keep things nice and neat.

**Comment by manthey** [comment]
As part of this, we'll want to move all issues to the appropriate repos.

**Comment by kheffah** [comment]
Yep, for sure.

**Comment by kheffah** [comment]
The only exception left is ``test_cli_result.py`` which was tweaked to use the .sha in PR #842 but still needs refactoring for dependence on girder.
