### ISSUE TITLE
pip installation error

### ISSUE THREAD

**Issue by rofa-metriter** [DigitalSlideArchive/HistomicsTK#825]
hey 

Trying to install  pickle in python 3.7
put :
!pip install pickle
output :
ERROR: Could not find a version that satisfies the requirement pickle (from versions: none) 
ERROR: No matching distribution found for pickle
thanks in advance for the help

**Comment by manthey** [comment]
pickle is a built-in module in Python.

**Comment by rofa-metriter** [comment]
thank you very much
