### ISSUE TITLE
Rendering of annotations in HistomicsTK front-end

### ISSUE THREAD

**Issue by cdeepakroy** [DigitalSlideArchive/HistomicsTK#83]
This issue is about adding the functionality necessary for rendering annotations on top of images in the HistomicsTK front-end.

@manthey and @jbeezley. Can one of you please take this up?

You can use some dummy annotations of each type to build the functionality necessary to render them.

**Comment by jbeezley** [comment]
If @manthey hasn't started on this yet, I can take it on.

**Comment by cdeepakroy** [comment]
Fixed by PR #103.
