### ISSUE TITLE
Install from source hung up

### ISSUE THREAD

**Issue by kheffah** [DigitalSlideArchive/HistomicsTK#847]
Installing from source gives this error:
```
ERROR: Could not find a version that satisfies the requirement mapnik (from large-image-source-mapnik; extra == "sources"->large-image[sources]->histomicstk==1.0.3.dev66+gfd966cfe) (from versions: none)
ERROR: No matching distribution found for mapnik (from large-image-source-mapnik; extra == "sources"->large-image[sources]->histomicstk==1.0.3.dev66+gfd966cfe)
```
I had to comment out the ``large-image`` line in ``setup.py`` and manually ``pip install large-image`` to be able to get things to work. Not sure if this is a histomicstk or large_image issue.

**Comment by kvijaysai** [comment]
I too had the same issue. After commenting large-image line in setup.py and manually pip install large-image. I am getting the below error:

 --------------------------------------------------------------------------------
    -- Trying "NMake Makefiles JOM (Visual Studio 15 2017 Win64 v141)" generator
    --------------------------------
    ---------------------------
    ----------------------
    -----------------
    ------------
    -------
    --
    --
    -------
    ------------
    -----------------
    ----------------------
    ---------------------------
    --------------------------------
    -- Trying "NMake Makefiles JOM (Visual Studio 15 2017 Win64 v141)" generator - failure
    --------------------------------------------------------------------------------
I have Visual Studio Build Tools 2019 16.5.1 version. Is this not sufficient? Or is the issue related to something else?

**Comment by manthey** [comment]
Some tile sources have complex library dependencies.  If you are on a linux system (Ubuntu, CentOS, etc.), you can add `--find-links https://girder.github.io/large_image_wheels` to your pip install command to install these dependencies from wheels.  If you are on OSX or another non-linux platform, you would need to install these libraries manually (you could do so on linux if you wanted anything other than the most recent versions, too).

We currently specify `large_image[sources]` as a requirement which installs all of the "standard" large_image tile sources, including mapnik.  We could be more specific specify tile sources explicitly, but then we'd have to adjust the setup.py file any time a new WSI tile source is added to large_image.

**Comment by manthey** [comment]
Although the use of `--find-links` is in the installation docs and README, perhaps we need to make it clearer.

**Comment by kvijaysai** [comment]
Mine is a Windows system. I don't think there is any problem with large-image library. I installed following all the steps mentioned in a Mac OS on my friends' laptop and it is working perfectly fine there.

Is there any issue with visual studio dependency on windows which is why I am unable to install. Can you please help me installing histomicstk with my windows system?

Also, if anybody has recently installed histomicstk from source on windows system, please let me know.

**Comment by kheffah** [comment]
@kvijaysai If you're using Windows 10, I think the better way to install from source is to use the ``bash`` comman prompt and to use the instructions provided here. @manthey can confirm this, but I'm don't believe this is meant to be installed using visual studio build tools.

**Comment by sdasara95** [comment]
@kheffah @kvijaysai @manthey 
Refer this link for the solution:
https://github.com/DigitalSlideArchive/HistomicsTK/issues/855
