### ISSUE TITLE
Implement CLI for segment nuclei and generate annotations for them

### ISSUE THREAD

**Issue by cdeepakroy** [DigitalSlideArchive/HistomicsTK#86]

**Comment by cdeepakroy** [comment]
@cooperlab I want to start working on this issue. Can you point me and @slee172 to the function to use for nuclei segmentation?

Also which of the two color deconvolution (standard/sparse) was working better so i could use that?

**Comment by cooperlab** [comment]
@cdeepakroy use the standard color deconvolution.

The function is really a sequence: normalize color -> deconvolve to hematoxylin (H) & eosin (E) -> mask -> cLoG response -> max clustering -> feature extraction.

I will write an example script if I get some free time tomorrow.

**Comment by cdeepakroy** [comment]
This is fixed by PRs #94 and #102.
