### ISSUE TITLE
Make girder_client optional

### ISSUE THREAD

**Issue by cooperlab** [DigitalSlideArchive/HistomicsTK#874]
A single function in HistomicsTK depends on girder_client:
https://github.com/DigitalSlideArchive/HistomicsTK/blob/master/histomicstk/utils/girder_convenience_utils.py

To simplify the build we should make girder_client optional.

Will need to update build instructions and note this in some of our examples (@kheffah).

**Comment by kheffah** [comment]
@cooperlab While only `connect_to_api()` uses `girder_client` per se, almost all the other functions in [girder_convenience_utils.py](https://github.com/DigitalSlideArchive/HistomicsTK/blob/master/histomicstk/utils/girder_convenience_utils.py) need to have an authenticated girder client as a non-optional parameter. These functions, in turn, are used particularly often in the database parsing and tissue tissue/cellularity detection modules.

**Comment by manthey** [comment]
I'll note that currently on pypi, version 1.0.5dev2 installs `girder_client` by default.  If we just make this an official release (just tag it in GitHub), then it would be version 1.0.5 and the installation would be automatic.  girder_client doesn't add much code or secondary dependencies.

**Comment by kheffah** [comment]
Closed since an official release was made so `girder_client` is now installed by default without extra dependencies.
