### ISSUE TITLE
Drop Python 2.7 and 3.5 support

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/HistomicsTK#888]
Python 2.7 and 3.5 are both well past end-of-life.  We should release current master as a new version in case anyone needs these older versions.  After that, we should remove these versions from published wheels and stop running CI on them.  We don't need to change any code, but after this we can use newer python features without concern and, eventually, strip out uses of the six library.

**Comment by manthey** [comment]
@kheffah, @cooperlab If you have any reservations about this, let me know.

**Comment by kheffah** [comment]
@manthey I concur. Thanks for asking.

**Comment by kheffah** [comment]
Is this related to the ci failures in PR #883 or #884 by any chance?

**Comment by manthey** [comment]
No; those were caused, at least in part, to changes to scikit-image AND changes to travis-ci.  If you now merge master (as of #885 and #886), those should pass (unless there are new failures caused by the branches).  While researching the fix for that, I noticed that we can now build for Python 3.9 since all of our dependencies are now built for it (see #887) which reminded me it was time to retire 2.7 and 3.5.

**Comment by kheffah** [comment]
I see, thanks for pointing this out and for making the updates. I've merged master into PR #884 and will let you know if it now passes.

**Comment by kheffah** [comment]
@manthey OK the job is waiting to run (hopefully) .. it says something about reaching the concurrency limit in circleci.
