### ISSUE TITLE
3rd party nuclear segmentation with pygco

### ISSUE THREAD

**Issue by cooperlab** [DigitalSlideArchive/HistomicsTK#89]
Implement end-to-end nuclear segmentation pipeline using the following components:
-Whole-slide Reinhard normalization
-Poisson mixture models / binary graph cuts
-Constrained log (cLoG) splitting to produce label image
-Multilabel graph cuts refinement to refine label image

**Comment by cdeepakroy** [comment]
This is now available in this [repo](https://github.com/cooperlab/NucleiCuts) of cooperlab.
