### ISSUE TITLE
typo in doc heading

### ISSUE THREAD

**Issue by kaczmarj** [DigitalSlideArchive/HistomicsTK#899]
Hi, thanks for this awesome project. I noticed a typo in https://github.com/DigitalSlideArchive/HistomicsTK/blob/master/docs/examples/introducing_the_girder_api.rst

"Introducing the gider API"

I can submit a fix for this but because this is a tiny thing, I didn't want to trigger continuous integration...

**Comment by manthey** [comment]
Thank you.  I've just corrected it.  You are welcome to submit fixes for anything else you find -- its okay to trigger CI even for doc updates.
