### ISSUE TITLE
Is it possible to add annotation programmatically 

### ISSUE THREAD

**Issue by rogertrullo** [DigitalSlideArchive/HistomicsTK#902]
Hi, I am starting to use the tool and so far I am able to make annotations through the web interface and then read them with histomickstk. However I have some annotations that have been done externally and I would like to add them to my dsa collection. Is this doable from histomickstk? is there any example? I can only find examples on reading but not writing them.
Thanks!

**Comment by manthey** [comment]
Yes.  There are REST endpoints for uploading annotations.  You can do it through the Girder UI by clicking the upload button on the Annotation bar (see image):
![image](https://user-images.githubusercontent.com/8781639/120477566-e8da1e80-c379-11eb-97d7-f5bace1eaf7a.png)
You can also use the `POST` `/annotation` or `POST` `/annotation/item/{id}` endpoints (see the Swagger/OpenAPI interface that you can reach via the Web API link for details).

**Comment by rogertrullo** [comment]
Thanks David, is there any example on this? I am confused on how to assign ids (is it just a random hex number?) and how to associate them with a given image.

**Comment by manthey** [comment]
When you post new annotations, if they don't have an ID, it will be assigned by the system.  This is done by MongoDB -- it isn't completely random; it has the current time and date encoded into it as well as a random component.  In theory, you could assign your own 24-digit hex number provided it doesn't clash with anything already present, but it is easier to let the system assign it.

When you upload an annotation via `POST` `/annotation` you have to specify an image ID.  When you do it via `POST` `/annotation/item/{id}`, the id is part of the path.

There are some examples in the Jupyter notebook examples (e.g., docs/examples/polygon_merger_from_tiled_masks.ipynb), in histomicstk/annotations_and_masks/masks_to_annotations_handler.py, histomicstk/annotations_and_masks/review_gallery.py, and probably elsewhere.

**Comment by rogertrullo** [comment]
This is really helpful thank you very much!
