### ISSUE TITLE
compute_haralick_features works incorrectly when `im_intensity` is a float with [0, 1] values

### ISSUE THREAD

**Issue by idc9** [DigitalSlideArchive/HistomicsTK#946]
My understanding of [compute_haralick_features](https://github.com/DigitalSlideArchive/HistomicsTK/blob/f737e1dd0010ade64069140c42c8c572a65a31a6/histomicstk/features/compute_haralick_features.py#L9) is that you can provide im_intensity as a 2d array of float intensity values between 0 and 1. However, as written, the function will **always** cast `im_intensity` to an int in [this line](https://github.com/DigitalSlideArchive/HistomicsTK/blob/f737e1dd0010ade64069140c42c8c572a65a31a6/histomicstk/features/compute_haralick_features.py#L289). This leads to incorrect behavior for [0,1] intensity valued images i.e. these will be binarized, which is not what we want to do. For example, most of the Haralick features end up being constant.

A simple fix would be to simply remove the `.astype(np.uint8)` i.e. 

```python
subImage = im_intensity[minr:maxr+1, minc:maxc+1]
```

I'm not sure what the purpose of casing subImage to np.uint8 -- is there a problem with removing this?

**Comment by cooperlab** [comment]
@idc9 this is addressed by #948 . We'll get this merged after the reviewer returns from travel.

**Comment by Aleksandr-Enin** [comment]
I've also encountered this problem, and at the very least it should be added in the documentation that the image has to be scaled to uint8 for compute_haralick_features to work properly.
