### ISSUE TITLE
Can I use tensort vector to complete the calculation

### ISSUE THREAD

**Issue by 464hee** [DigitalSlideArchive/HistomicsTK#971]

**Comment by manthey** [comment]
I'm not sure what you are asking.  What is a `tensort` vector?  What calculation?

**Comment by 464hee** [comment]
It should be a data format of Tensor and Pystore, supporting gpu calculation.Because histomicstk.processing.color_ normalization.deconvolution_ based_ It is too slow to use numpy in normalization

**Comment by 464hee** [comment]
It should be a data format of Tensor and Pytorch, supporting gpu calculation.Because histomicstk.processing.color_ normalization.deconvolution_ based_ It is too slow to use numpy in normalization

**Comment by 464hee** [comment]
I have hundreds of thousands of images, the size is 512 * 512, one image is 0.3s, and the time consuming is terrible

**Comment by cooperlab** [comment]
@464hee supporting GPU significant changes to the library. If this is the only routine you need, you can look at implementing this using CuPy or Torch. This function uses simple linear algebra operations and could be replicated without much effort.

**Comment by 464hee** [comment]
ok,Thank you for your advice
