### ISSUE TITLE
Guide for windows 11

### ISSUE THREAD

**Issue by abehzadnia** [DigitalSlideArchive/HistomicsTK#973]
After hours of frustration trying to get HistomicsTK installed and compiled properly on windows 11, a few additional steps to consider adding to the guide:

~~4- Install Visual Studio 15 2017 [Community Version](https://my.visualstudio.com/Downloads?q=visual%20studio%202017&wt.mc_id=o~msft~vscom~older-downloads)~~
~~5- Install C++ build tools. Under Tools > Get Tools and Features ... > Desktop Development with C++, ensure that the first 8 boxes are checked.~~

4. Instal Visual Studio 2022 Community edition with Build tools 
-  Ensure all the following optional tools are installed (especially Windows11 SDK)
- <img width="221" alt="image" src="https://user-images.githubusercontent.com/42820299/218050942-6e5a8477-d6b1-4957-b0b3-b80c859998ed.png">

6- Run this
```
$ python -m pip install -e .
$ pip install . 
$ python
import pyximport
pyximport.install()
import histomicstk
```
import pyximport **before** importing histomicstk, else you will run into errors when importing cython files.

Hope this saves you some headache!! :D

**Comment by dgutman** [comment]
Thanks for posting this.  Very few of the core admin team use windows for
primary development.   I do use wsl2 with Ubuntu on my windows machine and
it works well, If that's an option for you.
