### ISSUE TITLE
Syntax + rounding issues break gaussian_voting

### ISSUE THREAD

**Issue by idc9** [DigitalSlideArchive/HistomicsTK#975]
There are two issues that break  gaussian_voting 

https://github.com/DigitalSlideArchive/HistomicsTK/blob/d39f3053aa26fa7a811748c4176ad679b225bae7/histomicstk/segmentation/nuclear/gaussian_voting.py#L8

I run into a couple of issues when I try to run the gaussian voting algorithm. These are
1) it should be `Grad.dx` not `Grad.Dx` (e.g. see [this line](https://github.com/DigitalSlideArchive/HistomicsTK/blob/d39f3053aa26fa7a811748c4176ad679b225bae7/histomicstk/filters/edge/gaussian_grad.py#L54))

This shows up in [here](https://github.com/DigitalSlideArchive/HistomicsTK/blob/d39f3053aa26fa7a811748c4176ad679b225bae7/histomicstk/segmentation/nuclear/gaussian_voting.py#L72) and [here](https://github.com/DigitalSlideArchive/HistomicsTK/blob/d39f3053aa26fa7a811748c4176ad679b225bae7/histomicstk/segmentation/nuclear/gaussian_voting.py#L83)

2. The fact that [r is a float](https://github.com/DigitalSlideArchive/HistomicsTK/blob/d39f3053aa26fa7a811748c4176ad679b225bae7/histomicstk/segmentation/nuclear/gaussian_voting.py#L68) causes some shape/indexing errors. 

This shows up [here](https://github.com/DigitalSlideArchive/HistomicsTK/blob/d39f3053aa26fa7a811748c4176ad679b225bae7/histomicstk/segmentation/nuclear/gaussian_voting.py#L79) and [here](https://github.com/DigitalSlideArchive/HistomicsTK/blob/d39f3053aa26fa7a811748c4176ad679b225bae7/histomicstk/segmentation/nuclear/gaussian_voting.py#L89)

You can fix this easily by putting `round` around the the quantities that use r and define shapes or array indices.

**Comment by manthey** [comment]
@idc9 Thanks -- I made PR #978 to address this.

**Comment by idc9** [comment]
Thanks!
