### ISSUE TITLE
Bump girder, girder_worker and large_image in HistomicsTK/.travis.yml

### ISSUE THREAD

**Issue by cdeepakroy** [DigitalSlideArchive/HistomicsTK#98]
This issue is about bumping hash of girder, girder_worker and large_image to the latest commit in HistomicsTK/.travis.yml

**Comment by cdeepakroy** [comment]
@brianhelba I tried to do this in PR #94 to get some new features added to girder_worker but TravisCI throws this [error](https://travis-ci.org/DigitalSlideArchive/HistomicsTK/builds/132399102#L838-L843). This is probably due to a conflict with versions of Pillow between girder and large_image.

**Comment by brianhelba** [comment]
Fixed by #99 and #100 .
