### ISSUE TITLE
Recolour deconvoluted stains

### ISSUE THREAD

**Issue by EST09** [DigitalSlideArchive/HistomicsTK#992]
Hi, 

Thank you so much for histiomicstk. 

I'd love to use your [colour deconvolution example](https://digitalslidearchive.github.io/HistomicsTK/examples/color_deconvolution.html)
and then recolour the separated images back to respectively the original haem or eosin, so the separated images are no longer grayscale. I think I'm probably missing something already explained in the docs, but would it be possible to ask for help with that? 

Thank you

Best wishes, 
Emily

**Comment by cooperlab** [comment]
Emily,

I think this is what you are looking for:

https://digitalslidearchive.github.io/HistomicsTK/histomicstk.preprocessing.color_deconvolution.html#histomicstk.preprocessing.color_deconvolution.color_convolution

-Lee

**Comment by EST09** [comment]
Thank you so much for your help - I'm really sorry I think I'm still failing to understand though. Is it possible to just get the blue haem channel image displayed or the brown dab image rather than the gray scale? 

For example, 

new_im = htk.preprocessing.color_deconvolution.color_convolution(imDeconvolved.StainsFloat, imDeconvolved.Wc)

and then new_im is an array of shape (x, y, 3)

but I can't figure out how to display new_im[:, :, 0] as just a blue image i.e convert it into an rgb image displaying haem without dab

Is that possible at all? Thank you so much!

**Comment by cooperlab** [comment]
I understand what you want. I think you can just zero out the columns of `Wc` that you want to suppress. IIRC each of those columns is a color vector e.g. hematoxylin.

**Comment by EST09** [comment]
Thanks - could I please check that I've understood correctly?

```
#change im to 3 channels
im = np.array(im)
im = im[:, :, :3]
h, w, c = im.shape
imInput = im.copy()

# create stain to color map
stain_color_map = htk.preprocessing.color_deconvolution.stain_color_map

# specify stains of input image
stains = ['hematoxylin',  # nuclei stain
          'dab',        # ab stain
          'null']         # set to null if input contains only two stains

# create stain matrix
W = np.array([stain_color_map[st] for st in stains]).T

# create initial stain matrix
W_init = W[:, :2]

# Compute stain matrix adaptively
sparsity_factor = 0.5

I_0 = 255
im_sda = htk.preprocessing.color_conversion.rgb_to_sda(imInput, I_0)
W_est = htk.preprocessing.color_deconvolution.separate_stains_xu_snmf(
    im_sda, W_init, sparsity_factor,
)

# perform sparse color deconvolution
imDeconvolved = htk.preprocessing.color_deconvolution.color_deconvolution(
    imInput,
    htk.preprocessing.color_deconvolution.complement_stain_matrix(W_est),
    I_0,
)

Wc = imDeconvolved.Wc.T

H = np.matmul(htk.preprocessing.color_conversion.rgb_to_sda(imDeconvolved.StainsFloat[:, :, 0], 255).reshape(-1, 1), Wc[0, :].reshape(1, -1))
H = htk.preprocessing.color_conversion.sda_to_rgb(H, 255)
H = H.reshape(h, w, c)
H = H.clip(0, 255).astype(np.uint8)

D = np.matmul(htk.preprocessing.color_conversion.rgb_to_sda(imDeconvolved.StainsFloat[:, :, 1], 255).reshape(-1, 1), Wc[1, :].reshape(1, -1))
D = htk.preprocessing.color_conversion.sda_to_rgb(D, 255)
D = D.reshape(h, w, c)
D = D.clip(0, 255).astype(np.uint8)

B = np.matmul(htk.preprocessing.color_conversion.rgb_to_sda(imDeconvolved.StainsFloat[:, :, 2], 255).reshape(-1, 1), Wc[2, :].reshape(1, -1))
B = htk.preprocessing.color_conversion.sda_to_rgb(B, 255)
B = B.reshape(h, w, c)
B = B.clip(0, 255).astype(np.uint8)

#create a subplot of 5 figures (1 row, 5 columns)

fig, axes = plt.subplots(1, 5, figsize=(20, 20))

axes[0].imshow(imInput)
axes[0].set_title("Input Image", fontsize=titlesize)

axes[1].imshow(imDeconvolved.Stains)
axes[1].set_title("Deconvolved Stains", fontsize=titlesize)

axes[2].imshow(H)
axes[2].set_title("Hematoxylin", fontsize=titlesize)

axes[3].imshow(D)
axes[3].set_title("DAB", fontsize=titlesize)

axes[4].imshow(B)
axes[4].set_title("Background", fontsize=titlesize)

plt.tight_layout()

plt.show()
```
![9322fc96-6cb1-4354-8321-b86a423d57bc](https://github.com/DigitalSlideArchive/HistomicsTK/assets/25770709/a5eb995d-24d8-4f41-a07e-d9e1090adf0e)

**Comment by cooperlab** [comment]
Emily - I didn't check line-by-line but this output looks correct to me. Interestingly, you didn't need the color_convolution function.

**Comment by EST09** [comment]
Great - thank you!
