### ISSUE TITLE
Record parameters and primary results in annotation metadata

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/HistomicsTK#998]
We should record the parameters used and the primary results in annotation metadata wherever appropriate.

For instance, in PositivePixelCount, we do this in the annotation description: https://github.com/DigitalSlideArchive/HistomicsTK/blob/master/histomicstk/cli/PositivePixelCount/PositivePixelCount.py#L117 and the annotation attributes: https://github.com/DigitalSlideArchive/HistomicsTK/blob/master/histomicstk/cli/PositivePixelCount/PositivePixelCount.py#L118

For any of the CLIs where we generate annotations, we should definitely emit the command line parameters (e.g., `'attributes': {'params': vars(opts)}`).  We should consider each CLI in turn for what makes sense.

**Comment by subinkitware** [comment]
a new set of annotation parameters were added to the output file.
